### ISSUE TITLE
Missing channels on tvpassport

### ISSUE THREAD

**Issue by stuckinthe** [K-vanc/Tempest-EPG-Generator#101]
I am trying to download the guide for ktxa but it is not found in the tvpassport channel list. I looked on the https://github.com/iptv-org/epg/blob/master/sites/tvpassport.com/tvpassport.com.channels.xml site and it lists this channel. How can I get this channel into Tempest. I tried changing the zip code but it doesn't do anything and create channels.

**Comment by K-vanc** [comment]
GENERAL POINT BEFORE RAISING ISSUE (if not request)

1) Visit website 
2) Check if you can display everything normal on website
3) Enter your zip code and find the channel you are looking for on website
4) Check if channel exists and has epg on website
5) Use the zip code that you found, in Tempest to channel create
6) If no channel created => raise issue
7) If channel created but no epg generated (based on point 4) => raise issue
8) there is nothing I care about other softwares
9) there is nothing I can do for anything out of above points.. (including point 8)

Note: I checked website via remote vpn and there was nothing on the response related with zip code selection or provider lists.. It still may be related with geo-blocking and they may hunt my vpn down or website may change/delete zip code query

**Comment by K-vanc** [comment]
instead of you, I checked that channel "ktxa" in google and it was written located at Fort Worth TX so I search zip codes in that location and tried the first one I found(76006) in tvguide.com[US] siteconfig (because it is not geo-blocked) and found below results:

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/bedf3f56-989f-45ad-83be-d6f6721939ff)

**Comment by stuckinthe** [comment]
I checked and tried a Ft Worth zip code on tvpassport but not on tvguide. I will try on TV Guide.

**Comment by K-vanc** [comment]
I will check tvpassport when I have time. Probably they changed something
