### ISSUE TITLE
Taiwan mod epg url has been changed

### ISSUE THREAD

**Issue by Wangliann** [K-vanc/Tempest-EPG-Generator#102]
hi,
[mod.cht.com.tw_0.siteconfig.php](https://github.com/K-vanc/Tempest-EPG-Generator/blob/main/Siteconfigs/Taiwan/mod.cht.com.tw_0.siteconfig.php) 
The website was adjusted on April 1, and the php can no longer generate epg normally.
new url：[https://mod.cht.com.tw/program.do?id=9](https://mod.cht.com.tw/program.do?id=9)

**Comment by K-vanc** [comment]
Hi, updated
