### ISSUE TITLE
Skylink CZ not work

### ISSUE THREAD

**Issue by ericek74** [K-vanc/Tempest-EPG-Generator#103]
Can you check the Skylink CZ siteconfig?
Site: [ENC][EX]livetv.skylink.cz_0
 Channel id: Ux1UgS9P1EKZhmjWrQJ3uEkd_hZgQVpoPBuzzArI
Xmltv id: Sport1
[      Warning      ]
 No show grabbed in 0.19 seconds
[       Error       ] Request Error(url3): The requested URL returned error: 401
[       Error       ] Request Error(url3): The requested URL returned error: 401
[       Error       ] Request Error(url3): The requested URL returned error: 401
[       Error       ] Request Error(url3): The requested URL returned error: 401
thank you

**Comment by K-vanc** [comment]
Hi, updated
