### ISSUE TITLE
Be***.com site config hatalı?

### ISSUE THREAD

**Issue by Alma101** [K-vanc/Tempest-EPG-Generator#105]
be**.com.tr_ 0  site adresi güncel olarak bu şekilde başlıyor https://***rts.com.tr/yayin-akisi configde ise .tr/_next/data/390/tr-TR/yayin-akisi şeklinde yer alıyor. bu yüzden epg çekerken 404 hatası alınıyor. _next ile başlayan kısmı config editorden silmeyi denediğimde ise günler kaydı ilk defa githubda yazıyorum umarım anlatabilmişimdir iyi günler iyi çalışmalar.

**Comment by K-vanc** [comment]
Hocam, epg senin gordugun linkten gelmiyor. "/390/" olan yer degisti sadece. Guncel versiyonu tekrar indirebilirsin. Yalniz bu site surekli degisir ayrica 3 gun epg olur, sonraki 5 gun olmaz vs. Benim tavsiyem bu kanallari digiturk siteconfig dosyasindan kullanman
