### ISSUE TITLE
Albania tring.al

### ISSUE THREAD

**Issue by devhik** [K-vanc/Tempest-EPG-Generator#106]
![IMG_20240405_224942](https://github.com/K-vanc/Tempest-EPG-Generator/assets/119641432/7f29f45e-24a8-4c6a-85ef-699b621255d6)

**Comment by K-vanc** [comment]
Did you mean something?

**Comment by devhik** [comment]
> Did you mean something?

Sorry, it turns out there was a misunderstanding, I thought the config was no longer working, apparently it was geo-blocked, maybe you could include information in the config that there are geographic restrictions 🙏

**Comment by K-vanc** [comment]
Well, but i dont know they are geo-blocked or not if i can access without vpn 😀
