### ISSUE TITLE
tvguide yahoo problem

### ISSUE THREAD

**Issue by luongz** [K-vanc/Tempest-EPG-Generator#108]
## Issue Type

Please choose your issue type

* [x] Request
* [ ] Bug
* [x] Question

## OS Details (Not required for Request)

Please choose your OS

* [ ] Windows
* [x] Unix
* [ ] Docker

Hello there, Yahoo JP is shutting down their tv guide service, so the siteconfigs of Yahoo JP are not working right now.
![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/76716526/4657c888-733b-4dda-9b22-01f07adf424b)

Also , could you please add the location grab (like yahoo.jp) on the bangumi siteconfigs? I like to grab the TV guide of any prefecture in Japan.
![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/76716526/3b01ab49-070a-4b32-a6b3-149c1d883989)

Thanks you.

**Comment by K-vanc** [comment]
hi;

I thought that Yahoo Japan website has alternative epg but it is just a redirect for bangumi website and epg being fetched from there. In this case yahoo.jp siteconfig can be deleted from repo.

For location select, I am usually doing it when there are new/diff channels based on different locations or content of the channels(start/stop times, events etc.) are changing based on locations. As far as I remember, content and channels are same for bangumi but only order of the channels are changing so I didnt make it like this but I will check again. If i notice any difference or if you show me some difference related with location change(it is really hard for me to detect difference in Japanese 😄 ), I can rewrite siteconfig for location select

**Comment by luongz** [comment]
For NHK channels, the News program is exclusive depending on region. (if you watch NHK Tokyo, the news program will be Tokyo,...but not the same program at all.)

Japan has a news network system so other channels than NHK will broadcast the same content, but some programs are exclusive depending on region too. For example:
Fuji TV (FNN - Fuji News Network) and Ishikawa TV (FNN)

Fuji EPG :
![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/76716526/dd9a5033-b343-49aa-98a1-ceeefc696b78)

Ishikawa TV EPG:
![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/76716526/3339f7d5-4f8a-4ba1-b68b-9526e96a8dbf)

**Comment by K-vanc** [comment]
ok, tv.yahoo.jp deleted and bangumi updated for location based channel creation

**Comment by luongz** [comment]
by the way, how i can grab all EPG regions?

**Comment by K-vanc** [comment]
1 by 1 

Create channel list for 1 region
add all the channels into your configuration and save
Create channels list for another region
add all the channels into your same configuration and save
repeat above steps till you are satisfied 😄

**Comment by luongz** [comment]
> 1 by 1
> 
> Create channel list for 1 region add all the channels into your configuration and save Create channels list for another region add all the channels into your same configuration and save repeat above steps till you are satisfied 😄

im doing it rn XD , thanks you.
