### ISSUE TITLE
horizon.tv cz not work

### ISSUE THREAD

**Issue by ericek74** [K-vanc/Tempest-EPG-Generator#111]
Can you check the horizon.tv cz siteconfig?

(1/3) Site: [ENC]horizon.tv[Cz]_0
Channel id: lgi-obolite-cz-prod-master:10018
 Xmltv id: CT 1 HD
[      Warning      ]
No show grabbed in 0.14 seconds
[       Error       ] Request Error(url1): The requested URL returned error: 403
[       Error       ] Request Error(url1): The requested URL returned error: 403

 (2/3) Site: [ENC]horizon.tv[Cz]_0
Channel id: lgi-obolite-cz-prod-master:20185
 Xmltv id: Nova HD
[      Warning      ]
 No show grabbed in 0.01 seconds

thanks

**Comment by K-vanc** [comment]
hi, horizon.tv[CZ] was the last one still working from horizon.tv family but it seems they finally unplugged it also. so there is nothing to do or fix. Just use another siteconfig

**Comment by K-vanc** [comment]
hmm, my bad, horizon.tv for Slovakia is still active so it is the last one remaning. Maybe Czech version is active somewhere but I couldn't find any related url for it. If you have anything, just share so maybe we can make it alive again
