### ISSUE TITLE
Siteconfig Repair

### ISSUE THREAD

**Issue by NHKRoku** [K-vanc/Tempest-EPG-Generator#112]
Hello.
I seen that a mytv siteconfig in Vietnam folder have been damaged because the link's changed
So,can you repair a mytv siteconfig please
new link's here:https://mytv.com.vn/dich-vu/xem-lich-phat-song.html
thank you again.

**Comment by K-vanc** [comment]
I will verify this because there is geo-blocking now in website and not allowing to visit page out of Vietnam. This could be your issue if you are trying from another location

**Comment by NHKRoku** [comment]
year,it's geo-blocked
but when i use vpn to acess a page,it report,that not found
and i check that they have added prefix ''dich-vu'' in link
i seem that

**Comment by K-vanc** [comment]
Ok, I will try to check when I have time on with vpn on my own pc.

**Comment by NHKRoku** [comment]
i just checked source data and that have link is:https://apigw.mytv.vn/api/v1/channel/##channel##/schedule?date=##urldate1## with date format is y-m-d.
you can try extract with this url

**Comment by K-vanc** [comment]
maybe channel ids are also changed? No success with; 

https://apigw.mytv.vn/api/v1/channel/1/schedule?date=24-04-22

as 1 is channel id of VTV1

**Comment by NHKRoku** [comment]
Yep,you have some error when typing url
Here's a sample of VTV1 channel:https://apigw.mytv.vn/api/v1/channel/210/schedule?date=2024-04-22
You can rewatch a day format
Hope your reply

**Comment by NHKRoku** [comment]
sorry it's my fault
a channel id just to replace to get data
i'll sent you,please wait me

**Comment by K-vanc** [comment]
so there is no url for channel generation? In this case, better I check to make siteconfig dynamic

**Comment by NHKRoku** [comment]
a year,because of geo-blocked,i think you can you web proxy for this tasks
link here,you don't need vpn to acess this:https://www.congcuweb.net/?q=https://mytv.com.vn/dich-vu/xem-lich-phat-song.html

**Comment by NHKRoku** [comment]
a year,because of geo-blocked,you can try this tip to access a page:
you go to https://www.congcuweb.net and type:https://mytv.com.vn/dich-vu/xem-lich-phat-song.html to access page
hope this will help you

**Comment by K-vanc** [comment]
lol I need another proxy to access your proxy website 😄 it is being blocked by my company firewall

**Comment by NHKRoku** [comment]
Hmm,ít look like difficult to find a page that can on your firewall
But i finded another proxy that you can try,link here:http://proxy.tuoitreit.vn

**Comment by NHKRoku** [comment]
a little aside, do you still remember that I asked you about cachup in EPG?
Actually,I've a japan epg Link:http://103.255.250.202:11004/epgs/channel/epg/get?id=gd01&date=##urldate1## <<Y-m-d>>
If go to the next day,it's a normal epg but if go to the past that have url to timeshift a program

**Comment by K-vanc** [comment]
> a little aside, do you still remember that I asked you about cachup in EPG?
> Actually,I've a japan epg Link:http://103.255.250.202:11004/epgs/channel/epg/get?id=gd01&date=##urldate1## <<Y-m-d>>
> If go to the next day,it's a normal epg but if go to the past that have url to timeshift a program

Well, dont remember that but for sure I replied as you cannot grab old days because Tempest will ignore them but you can generate an updating epg file with catch-up upto 15days. All you need to do is enabling Fusion mode on your configuration file and setting fusion level as how many days you want exp level 5 means catch-up upto 5days. So you need to keep grabbing with this file and after 5days, your xml file will contain newly grabbed shows + 5days catchup data. Both new and catchup days will be updated on your next runs so if you daily grabbing, file will be always updated with  5 days catchup

**Comment by NHKRoku** [comment]
See hard to fi

**Comment by NHKRoku** [comment]
[Uploading Channel list.docx…]()

**Comment by NHKRoku** [comment]
Sorry, I have the wrong word, vtv1 channel id is 210, not 211, which is vtv3 channel. Hope you can correct it.

**Comment by K-vanc** [comment]
Hi,

I was in busy days at work so couldn't even have time for days to check what is going on. I tried with my VPN on Vietnam location but website detected it and blocked.. I tried also your proxies but none of them worked properly by loading the page. As far as I see, channel details are not available on loaded page below;

https://mytv.com.vn/dich-vu/xem-lich-phat-song.html

or channel details are being loaded/injected by another ajax/javascript after passing location check.. I cannot update siteconfig in repo without channel creation part. If you need I will attach here template siteconfig with epg grabbing only;

[mytv.com.vn_0.siteconfig.txt](https://github.com/K-vanc/Tempest-EPG-Generator/files/15137040/mytv.com.vn_0.siteconfig.txt)

Don't forget to change file extension as php again. And If you believe channel details are above page for you, please run it on channel creation debugger with debug into file option and send me created txt file so I can check and fix channel creation part;

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/ce8eb5bc-9725-4bd6-9735-86a20e1ae1f4)

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/0e212958-9913-4729-8e60-d3eab40627b0)

created file will be inside /tempest_config/log/ directory

**Comment by NHKRoku** [comment]
yeah,i've been completed
[mytv.com.vn_0.channel.txt](https://github.com/K-vanc/Tempest-EPG-Generator/files/15137697/mytv.com.vn_0.channel.txt)

**Comment by K-vanc** [comment]
and you have log file with page response?

**Comment by NHKRoku** [comment]
I'm sorry,I'm not get with the instruction,I use my data have done it before like the table I sent above.

**Comment by K-vanc** [comment]
i attached 1 siteconfig above, if you want to help, you will copy/paste it into your site_config folder then go to Siteconfig Debugger and choose/enable the options that I showed in photos. As a result, Tempest will create a log.txt file in /log/ folder. If you send me that file, I can make siteconfig dynamic for channel creation. If not, it is ok

**Comment by NHKRoku** [comment]
Hmm,I had following your instruction,but I couldn't receive any usefull data
[Tempest_debugger.txt](https://github.com/K-vanc/Tempest-EPG-Generator/files/15138102/Tempest_debugger.txt)

**Comment by K-vanc** [comment]
ok, thanks. so channel information is somewhere else but cannot find out till find a way to check website by myself. That siteconfig will work with your channel list for epg grabbing

**Comment by NHKRoku** [comment]
i see that channel id is located in channel list but it only show in development tool
![Screenshot 2024-04-27 192531](https://github.com/K-vanc/Tempest-EPG-Generator/assets/134927860/07db8a20-6774-4407-9b70-2c1edee9df68)

**Comment by K-vanc** [comment]
You need to use "Network" tab and then click refresh so some urls will be loaded under fetch/xhr and doc tabs. Channel list should be somewhere there

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/7969f8ef-fe36-492e-8836-7038f0543bee)

**Comment by K-vanc** [comment]
I think I found the link but cannot see its content


https://webapi.mytv.vn/api/v1/footer/channel?common_text=mytv-app&uuid=0e99b6d8f245c1d04e332b18e0663bc2&time=2024y04m27d_16h16m24s935ms

**Comment by NHKRoku** [comment]
finally,i finded a channel link
it here:https://apigw.mytv.vn/api/v1/channel

**Comment by K-vanc** [comment]
New version uploaded into Vietnam folder. Thanks for your contribution
