### ISSUE TITLE
Request to update [ENC]jiotv_0.siteconfig.php in Indian Folder

### ISSUE THREAD

**Issue by simperpie** [K-vanc/Tempest-EPG-Generator#114]
Hey K-Vanc,

As you mention in Remarks of **[ENC]jiotv_0.siteconfig.php** "Since Jio TV requires active subscription, this siteconfig uses "mitthu786 / tvepg" github project as source".
JioTV just changed their API , previous one is not working more. Now can access tv guide from website directly.
Kindly update this whenever you have free time.

**Updated Link**
https://www.jiotv.com/tv-guide

Thanks

**Comment by K-vanc** [comment]
I will check later because seems still geo-blocked for me

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/458041de-023e-4a65-9139-c47eed99abe9)

**Comment by simperpie** [comment]
ok

**Comment by K-vanc** [comment]
Hi,

English and Hindi versions added into India folder.

Note: Website is geo-blocked so suitable ip adress required

**Comment by simperpie** [comment]
Thanks
