### ISSUE TITLE
Request to update [ENC][EX]sky.de_0

### ISSUE THREAD

**Issue by cyb3rgh05t** [K-vanc/Tempest-EPG-Generator#115]
possible to update [ENC][EX]sky.de_0 in german folder?

```Request Error(url1): The requested URL returned error: 403```

Thanks

**Comment by K-vanc** [comment]
Hi,

I don't see any problem on siteconfig. it all runs fine.

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/b113ab20-a90c-4757-a864-8bc23d1024d9)

If you fulfill the issue template properly for make me understanding your tempest version, OS, php version etc. and which channel is not working for you.. Maybe I can help to resolve your side problem.. Because your pasted "error" has no meaning without this information..

**Comment by K-vanc** [comment]
just to mention, 403 code means forbidden from server side. usually happens when website blocks your ip adress for some reason such as burst or flood requests etc and usually resolves by itself after waiting period or refreshing your ip adress

**Comment by cyb3rgh05t** [comment]
ah ok thanks for this information. i will check again if the error presists or not

**Comment by cyb3rgh05t** [comment]
![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/5200101/50b4bd6e-dacb-4004-bf6b-26f066ce5784)

still on 403 error

i am on ubuntu 20.04
latest tempest version

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/5200101/725d7925-122d-4ea1-a3ef-9c25c2280566)

**Comment by K-vanc** [comment]
You are still receiving 403 error which means you have been banned by website. Usually these bans are for limited times such as a few hours or a day but hard to know how long it will be blocked. If you have a vpn or proxy, just try again with it and you will see it is working fine

**Comment by K-vanc** [comment]
I think you are using a shared host so this could probably be a bad neighbour effect as you have been blocked due to some other user's actions since you are in the same ip block

**Comment by cyb3rgh05t** [comment]
it is a dedicated root server i am the only person using it

**Comment by cyb3rgh05t** [comment]
how can i setup a proxy for tempest?

**Comment by cyb3rgh05t** [comment]
great got it thanks :) donations?

**Comment by cyb3rgh05t** [comment]
just another question. why do some siteconfig have a expire time?

**Comment by K-vanc** [comment]
> great got it thanks :) donations?

welcome. Donations are not mandatory or requested by me. Have a look below;

[DECLARATION.md](https://github.com/K-vanc/Tempest-EPG-Generator/blob/8528ee3b96a62eac6d3561336d5ca33a92a1514c/DECLARATION.md)

If you still want to, you can use github sponsor option as you wish

**Comment by K-vanc** [comment]
> just another question. why do some siteconfig have a expire time?

Short answer is I like to torture people and sometimes myself

Long answer is protect websites and myself as to make some of this siteconfigs work, you need to bypass several security levels and not sure if they are legal or not. So if i get a complain from website, I will delete file from repo and file will be useless after expiry date.

**Comment by cyb3rgh05t** [comment]
ok thanks

**Comment by cyb3rgh05t** [comment]
hmmm even if i add add a sock5 proxy it throws me the error

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/5200101/551c0dd0-16db-42b2-b559-6007d4b3ad69)

but he proxy works
![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/5200101/02352dfc-50a3-4925-a7f2-09b546f63530)

**Comment by K-vanc** [comment]
because you are using wrong protocol. socks5 for ip adress:port. If you want to use host name than your protocol shall be socks5h:// to resolve host name

**Comment by cyb3rgh05t** [comment]
my bad sorry

**Comment by cyb3rgh05t** [comment]
hmmm that also doesnt work :(

```socks5h://test:test@146.59.35.180:1080```

i made a test user config could you mabye try it out please?

**Comment by K-vanc** [comment]
if you are using ip adress as numbers, it should be socks5 but instead if you are using name(such as dynamic dns, it should be socks5h.

I will try now

**Comment by K-vanc** [comment]
this is what I get with your proxy
![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/0d05cff5-e4e4-4508-900b-14079b3dee3c)

It is 403, means your proxy address is also blocked by website. and below without any proxy/vpn since my adress is probably in whitelist

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/903bb4cb-d6b7-4423-91a6-dbf732bdbc20)

**Comment by cyb3rgh05t** [comment]
ok thanks i will check that out thanks

**Comment by K-vanc** [comment]
well, there are tons of ways to identify and block a user by ip adress, mac adress, some other cookie or javascript injection, user-agent value, ssl handshake fingerprint so this is a war that mostly you will lose. If there is nothing very important in this website, just step back and continue with other working options. after some time it will be work again.

I remember that magenta was blocked my raspberry pi once for 2,5 months. it was working in all my other devices in the same network except raspberry. Still dont know how they identified and blocked only that device

**Comment by cyb3rgh05t** [comment]
ok i see but could you please explain me this?

```if you are using ip adress as numbers, it should be socks5 but instead if you are using name(such as dynamic dns, it should be socks5h.```

i do not understand what you really mean :(  for me this is a numbered ip address:

```socks5h://test:test@146.59.35.180:1080```

**Comment by K-vanc** [comment]
socks5://test:test@myverygoodproxy.com

socks5h://test:test@146.59.35.180:1080

On your previous screenshot, I saw as you are using host name under red line but checked again, it was my bad as it was numeric

**Comment by cyb3rgh05t** [comment]
ah ok i undestand now :) sorry

**Comment by cyb3rgh05t** [comment]
is it normal taht it takes so much time to grab shows for a channel?

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/5200101/6d504224-c15b-4d64-a9f1-e29c20b65a4e)

**Comment by K-vanc** [comment]
Yes, if you are using detail page siteconfigs.. for a single channel with 800+ shows, Tempest making 800+ additional page request and processing their data. If you use all-index siteconfig or enable index-only grabbing from your configuration file, it will grab much more faster. But for some siteconfigs detail pages are mandatory. Check below post for understanding better;

https://github.com/K-vanc/Tempest-EPG-Generator/issues/15#issuecomment-1467329319

**Comment by K-vanc** [comment]
Also update your Tempest version by using Tempest Updater
