### ISSUE TITLE
this one can be add like siti  file?

### ISSUE THREAD

**Issue by Toei79** [K-vanc/Tempest-EPG-Generator#12]
`https://www.directv.com.co/guia/guia.aspx`

this one can be add it? its for colombia 

thanks!

**Comment by K-vanc** [comment]
Hi, for sure. It can be done since I already did other directv siteconfigs but problem is website is geoblocked and currently I am using company pc which vpn not allowed. I added it to my to-do list but you need to wait abit till I reach my personel pc back

**Comment by Toei79** [comment]
> Hi, for sure. It can be done since I already did other directv siteconfigs but problem is website is geoblocked and currently I am using company pc which vpn not allowed. I added it to my to-do list but you need to wait abit till I reach my personel pc back

Oh 👍great

Wondering  thats europe?

I mean this one its for colombia  , and I'm usa

Never thought  get geoblock on epg stuff

Thx

**Comment by K-vanc** [comment]
Hi, it is added to Colombia folder. Please check then I will close the issue

**Comment by Toei79** [comment]
thanks its working fine!

**Comment by K-vanc** [comment]
Welcome. Issue closed
