### ISSUE TITLE
DTV Chile

### ISSUE THREAD

**Issue by maurioski** [K-vanc/Tempest-EPG-Generator#120]
## Issue Type

Please choose your issue type

* [X] Request
* [ ] Bug
* [ ] Question

* [ ] Windows
* [X] Unix
* [ ] Docker

## Attachments (Not required for Request/Question)

Can add this EPG from Chile DTV?

https://www.directv.cl/guia/guia.aspx/GetProgramming 
![Screenshot_17](https://github.com/K-vanc/Tempest-EPG-Generator/assets/67890430/6a4cc166-e03d-4b71-b6ba-972e1e1a5682)

**Comment by K-vanc** [comment]
Hi @maurioski;

As I explained to you under several topics, directv for South America(this includes Chile as well), is using an additional security level which we cannot bypass. Web browsers are designed to resolve all this javascript challenges in background with sacrifice of page opening times. It is not always working same to see an url in browser and calling same url with a wget/curl etc. request. Below request has been redirected to that security layer while I just called epg url..

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/424627c8-3ed2-475f-8ebf-ee40d7b17564)

So again I said, there will be no siteconfig for directv - South America till they remove that security layer

https://github.com/K-vanc/Tempest-EPG-Generator/issues/70#issuecomment-1928744001

https://github.com/K-vanc/Tempest-EPG-Generator/issues/93#issue-2170403373
