### ISSUE TITLE
Skylink SK

### ISSUE THREAD

**Issue by Radoorech** [K-vanc/Tempest-EPG-Generator#124]
Hi, Can you check the Skylink SK siteconfig?
Site: [ENC][EX]livetv.skylink.sk_0
Channel id: Jt5eIyf94-ba79agj8o1ZReVlDfA9wQlKeWJ17LP
Xmltv id: Jednotka HD
[ Warning ]
No show grabbed in 0.10 seconds
[ Error ] Request Error(url3): The requested URL returned error: 401
[ Error ] Request Error(url3): The requested URL returned error: 401
[ Error ] Request Error(url3): The requested URL returned error: 401
[ Error ] Request Error(url3): The requested URL returned error: 401

Maybe the same problem as Skylink CZ.

Thank you.

**Comment by K-vanc** [comment]
Hi,

Yes, they made similar changes on all websites belongs to them. all updated
