### ISSUE TITLE
Singapore starhub

### ISSUE THREAD

**Issue by Wangliann** [K-vanc/Tempest-EPG-Generator#125]
Hi, 
[Starhubtvplus.com_0.siteconfig.php](https://github.com/K-vanc/Tempest-EPG-Generator/blob/main/Siteconfigs/Singapore/%5BENC%5D%5BEX%5Dstarhubtvplus.com_0.siteconfig.php) in Singapore seems to be not working.

Site: starhubtvplus.com
Channel id: 855
Xmltv id: Hub VVDrama HD
No show grabbed in 7.23 seconds
Request Error(url1): OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.starhubtvplus.com:443
Request Error(url1): OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.starhubtvplus.com:443
Request Error(url1): OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.starhubtvplus.com:443
Request Error(url1): OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.starhubtvplus.com:443
Request Error(url1): OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.starhubtvplus.com:443

**Comment by K-vanc** [comment]
Hi, 

I think we have already discuss this issue with you some time ago. You are getting ssl error so problem is most probably on your server side;

https://github.com/K-vanc/Tempest-EPG-Generator/issues/31#issuecomment-1651059618

Did you check here as reminder?

**Comment by Wangliann** [comment]
Starhub has been working normally before, but this problem started in May

**Comment by Wangliann** [comment]
I've tried switching to different proxies. But if it's normal on your side,  that’s must be my server’s problem.

**Comment by K-vanc** [comment]
I will check and tell you. Now i am away from pc

**Comment by K-vanc** [comment]
yes, it is not working. also website epg is now completely behind the login. Last time I found a way to bypass but it seems that solutions is not working anymore. I will check again when I have more time but it could be end of game for it, this time

**Comment by Wangliann** [comment]
OK. Looking forward to having the opportunity to repair it in the future.
Thank you！

**Comment by K-vanc** [comment]
I hope I will not be arrested for such stupid reason like getting epg data but I literally broke their api..

Exclusive to Tempest only..
