### ISSUE TITLE
[Bug] no results for sky.at and sky.de siteconfig

### ISSUE THREAD

**Issue by cyb3rgh05t** [K-vanc/Tempest-EPG-Generator#128]
Tempest Version : rv1.7.0.0-2405061442
System Info : Linux  Uuntu 20.04
PHP Version : 8.2.12.
Server Info : Command Line Interface (Cli)

hi, 

i think there is an issue with the ```sky.at``` and ```sky.de``` sitconfigs

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/5200101/84d75873-8019-48ae-970a-7c62b29ddcd0)

Grabbing Epg results in 0 shows grabbed

**Comment by K-vanc** [comment]
Hi;

Siteconfigs are working fine but there is no epg in WEBSITE for those channels..

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/7f38f890-9dda-491d-82f6-de99dcd72857)

I rechannel create and also those channels are not available in the new channel list so..

Will you call this as "BUG"? 

Tempest is only a grabber.. It cannot provide you epg if there is no data in the source...

**Comment by cyb3rgh05t** [comment]
yes you right isnt a BUG but i didnt know how to call it :) sorry for that
