### ISSUE TITLE
digea.gr siteconfig says no guide data found

### ISSUE THREAD

**Issue by backyard-bbq** [K-vanc/Tempest-EPG-Generator#129]
I am getting no guide data found in my logs but I go to the website and see guide data. Can you take a look at it?

**Comment by K-vanc** [comment]
Hi, i am away from my pc but as far as I see, everything on website is same with siteconfig except a new cookie challenge. I will take a look when i am back. Probably it will be an easy fix but you need to wait a few days more

**Comment by K-vanc** [comment]
hi, updated
