### ISSUE TITLE
Channel generator with zipcode

### ISSUE THREAD

**Issue by Toei79** [K-vanc/Tempest-EPG-Generator#13]
hi i cant make this run, everytime it freezes like the second pic.  i add zipcode or name of state like txt file but

i tried with miami/fl => Miami, FL and just with Miami,fl

![01-29-2023 (004445)](https://user-images.githubusercontent.com/79808610/215307576-83259cea-8f82-458c-8842-61d897a0f141.jpg)
![01-28-2023 (221316)](https://user-images.githubusercontent.com/79808610/215307590-0e0c4bb7-cbf3-4e0d-b3cd-65d8f6007552.jpg)

i tried tvguide.io and flixed.io still same.  i have all dependencies installed.

im understanding that generate channel give me channels for my zipcode location instead the default one new york.

**Comment by K-vanc** [comment]
hi. It seems you tried every possible wrong combination :) First, please delete rev99 which was shared as testing purpose and redownload updated rev0

There is a special information file as below;

https://github.com/K-vanc/Tempest-EPG-Generator/blob/main/Siteconfigs/USA/0_Info%20for%20tvtv.us%20-%20tvpassport%20-%20tvguide%20-%20ontvtonight%20-%20%20directv%20-%20online-tivo%20-%20whattowatch.md

USA zip codes are 5 digit numbers such as 10001 for New York

**Comment by Toei79** [comment]
> hi. It seems you tried every possible wrong combination :) First, please delete rev99 which was shared as testing purpose and redownload updated rev0
> 
> There is a special information file as below;
> 
> https://github.com/K-vanc/Tempest-EPG-Generator/blob/main/Siteconfigs/USA/0_Info%20for%20tvtv.us%20-%20tvpassport%20-%20tvguide%20-%20ontvtonight%20-%20%20directv%20-%20online-tivo%20-%20whattowatch.md
> 
> USA zip codes are 5 digit numbers such as 10001 for New York

how long it takes?

i try with this one 33023 or 33101 but i still get same like the pic, also i deleted 99 one and use the 0 one and flixed too.

**Comment by Toei79** [comment]
oh i redownload now those files . thanks

**Comment by Toei79** [comment]
still getting the same i replace all ini files from usa folder and replace in the one that runs by tempest

**Comment by K-vanc** [comment]
Grabbing time changes based on available provider numbers 15 seconds to 1-2 minutes. Could you try after restarting your php server?

**Comment by Toei79** [comment]
i do a reboot now and see what happens

**Comment by K-vanc** [comment]
i am able to grab within 20 seconds fir zip code 33023

![image](https://user-images.githubusercontent.com/97025515/215308871-b223b2d3-007f-476b-bcc9-1bae243d9319.png)
![image](https://user-images.githubusercontent.com/97025515/215308885-0598dff1-e6e7-4329-951c-d850a06d5c67.png)

**Comment by Toei79** [comment]
maybe its my server? im using ngnix but need move files there to html to run , im not very expert honestly.  but i get xml with the other stuff i mean channels, but not yet with zipcode. 


https://user-images.githubusercontent.com/79808610/215309243-a55bb0cf-3ca5-474d-b956-8b3188c485b5.mp4

**Comment by K-vanc** [comment]
So you are in linux enviroment. Just to be sure, Could you please chmod/chown entire folder with proper file permission and ownership? 

Then, are you able Generate channel/grab from only [ENC] prefixed siteconfigs?

It seemed to me you have permission issue because it cannot freeze, new time challenge will be time out in 30 seconds and operation will be terminated in case of failure.

Also Could you try to visit website(tvguide.com) from your browser, if possible from the same device where you run Tempest?

**Comment by Toei79** [comment]
which its proper ownership +x?

**Comment by Toei79** [comment]
![01-29-2023 (014916)](https://user-images.githubusercontent.com/79808610/215310051-8a27fe2b-1851-49f1-a43b-48b14492fc16.jpg)

**Comment by Toei79** [comment]
![01-29-2023 (015212)](https://user-images.githubusercontent.com/79808610/215310176-efac9748-370c-4e0d-ab0b-1c2ffdcf2307.jpg)
ubuntu its the user in my server.

**Comment by K-vanc** [comment]
Some Of them seems wrong. Default user name of Nginx is www-data so for testing please run below 2 commands and check again;

sudo chown -R www-data:www-data /var/www/html
sudo chmod -R 777 /var/www/html

If solves the issue, it means permission error so you can find your best permission setup later by trying

**Comment by Toei79** [comment]
That resolved instantly , im really new on linux thanks!

question i have something elser running there that be fine?

**Comment by Toei79** [comment]
![01-29-2023 (020612)](https://user-images.githubusercontent.com/79808610/215310797-044f0bf8-6195-4f57-a0e3-21c18cca6303.jpg)
flixed.io i get this, its normal? i try with 33023 and miami/fl => Miami, FL from flixed io codes

**Comment by Toei79** [comment]
its anyway you can add https://tvlistings.zap2it.com/?aid=gapzap

i dont know feels more accurate than tvguide at least in usa, tvguide have some channels that already gone no longer exits. at least in broadcast part

thanks again for all help.  i never thought such program exists.  hoping learn this to scrap radio stations.

**Comment by K-vanc** [comment]
> ![01-29-2023 (020612)](https://user-images.githubusercontent.com/79808610/215310797-044f0bf8-6195-4f57-a0e3-21c18cca6303.jpg) flixed.io i get this, its normal? i try with 33023 and miami/fl => Miami, FL from flixed io codes

For flixed, you should follow its own instruction as below;

https://github.com/K-vanc/Tempest-EPG-Generator/blob/main/Siteconfigs/USA/0_info%20for%20flixed.io.md

it is creating its own list of codes on empty run so you need to enter as shown on picture.

Please note that there is some error on their server for awhile and when happens it always replies with same channel list regardless of what you entered. It is not a Tempest bug

**Comment by K-vanc** [comment]
> That resolved instantly , im really new on linux thanks!
> 
> question i have something elser running there that be fine?

Welcome, I am closing issue as resolved

**Comment by K-vanc** [comment]
> its anyway you can add https://tvlistings.zap2it.com/?aid=gapzap
> 
> i dont know feels more accurate than tvguide at least in usa, tvguide have some channels that already gone no longer exits. at least in broadcast part
> 
> thanks again for all help. i never thought such program exists. hoping learn this to scrap radio stations.

I will have a look but it seems geo-blocked
