### ISSUE TITLE
[REQUEST] EUROPACUP MAGENTA TV EPG

### ISSUE THREAD

**Issue by cyb3rgh05t** [K-vanc/Tempest-EPG-Generator#132]
HI :)

On magenta tv germany they published 3 new channels for the europacup 2024.

![photo_2024-06-14_18-55-05](https://github.com/K-vanc/Tempest-EPG-Generator/assets/5200101/c5df4e7e-24c6-43de-a9f8-3c1b45b29806)

is it possible to add the epg for these 3 channels in the ```web.magentatv.de``` siteconfig?

**Comment by K-vanc** [comment]
Hi,

I am not updating channel lists in repo but all siteconfigs are supporting dinamic channel list creation so all you need to do is choosing web.magenta siteconfig on Channel Generator and click generate. As far as I see, those channels will be included in new list

![Screenshot_20240614_212759_Chrome.jpg](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/bb038d22-3f53-47df-95b4-40d3162ab59b)

**Comment by cyb3rgh05t** [comment]
cool thanks

**Comment by cyb3rgh05t** [comment]
hmmm i get "no channel block found"

**Comment by cyb3rgh05t** [comment]
![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/5200101/650d7fde-37e3-4cfc-8f84-313af62a8d35)
![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/5200101/a4cf778c-e93f-440d-87bd-ecf63eb3472b)

**Comment by K-vanc** [comment]
Just keep trying. It is working but website ip banning. My ip also is also blocked but able to create channels list after trying 10-15 times

**Comment by cyb3rgh05t** [comment]
ok thanks
