### ISSUE TITLE
Repair Siteconfig

### ISSUE THREAD

**Issue by NHKRoku** [K-vanc/Tempest-EPG-Generator#134]
Hello,It's me again 
In one time I check siteconfig Monthly,i seem that on Vietnam tab,VTVcab siteconfig that can't receive,when I check,not only the link is changed,they also change the type of EPG website to XML on HTML format.
Link's here:https://dichvu.vtvcab.vn/broadcast
So,can you repair VTVcab siteconfig again please
Thank you again.

**Comment by K-vanc** [comment]
hi,

Updated
