### ISSUE TITLE
Fox chanels no longor exist (Star)

### ISSUE THREAD

**Issue by flavio5121** [K-vanc/Tempest-EPG-Generator#135]
In Portuguese standings, Fox channels was replaced for Star channels, so they can´t get any program from them

**Comment by Toei79** [comment]
As part of the March 2019 agreement between News Corp and Disney, FOX entertainment channels in Europe are now rebranding under the Star name that Disney has also adopted within the Disney+ app. Fox Corporation retained FOX News Media, FOX Sports, FOX Entertainment, FOX Television Stations and Tubi Media Group.Oct 29, 2023

you still get fox?

**Comment by K-vanc** [comment]
good morning guys and thanks for the inforamations but I don't understand how can I help you regarding this issue?? If channels are renamed in the sources, you will get them on re-channel creation. Tempest cannot edit satellite/broadcasting names of channels or provide epg if there is no data in the sources.

**Comment by K-vanc** [comment]
I am closing issue since no response
