### ISSUE TITLE
TURK EPG DONT WORK

### ISSUE THREAD

**Issue by gio299** [K-vanc/Tempest-EPG-Generator#136]
## Issue Type

Please choose your issue type

* [ ] Request
* [ ] Bug
* [ ] Question

## OS Details (Not required for Request)

Please choose your OS

* [ ] Windows
* [ ] Unix
* [ ] Docker

Please write your version details (Below not required for Docker)

* PHP Version: ...

* Tempest Version: ...

Please write your web server name(Apache/Nginx etc.) or tick shared host if you are running on a shared host service / server (VPS, Web Hosting etc.)

* Web Server Name: ...

* [ ] Shared Host

## Expected Behavior (Not required for Request)

Please describe the behavior you are expecting

## Current Behavior (Not required for Request)

Please describe the current behavior

## Steps to Reproduce (Not required for Request/Question)

Please explain how to reproduce this issue

## Attachments (Not required for Request/Question)

Please attach your error/grab logs, configuration.xml file

**Comment by K-vanc** [comment]
good morning.

How you managed to raise an issue without giving a single information about problem? 😄 

Please write what is not working for you and what is your operating system. I dont know what you mean by "TURK EPG" but they are working fine for me..

**Comment by K-vanc** [comment]
I am closing the issue since no response
