### ISSUE TITLE
Beware: Malware in tempest.php

### ISSUE THREAD

**Issue by w64** [K-vanc/Tempest-EPG-Generator#137]
tempest.php downloaded from the Releases section of this Github repository. After scheduled scan for malware, The antivirus app show that:

> Warning	06.07.2024	08:46:21	System	127.0.0.1	localhost	[Malware Remover] Removed the detected malware: **MR2101 (Bitcoin miner)**.

After some testing i have found that my copy of tempest.php is missing, so i downloaded it again and put it in the same location. After that i started scanning manually and what happened? Again the same malware have been detected. Maybe the author have put some present in php file. Be warned!!!
![NAS](https://github.com/K-vanc/Tempest-EPG-Generator/assets/5788060/4e981b15-b92e-4264-8a07-cda3625756d1)

## OS Details (Not required for Request)

Please choose your OS

* [ ] Windows
* [X] Linux
* [ ] Docker

Please write your version details (Below not required for Docker)

* PHP Version: 5.6.40

* Tempest Version: 1.7.0.0

Please write your web server name(Apache/Nginx etc.) or tick shared host if you are running on a shared host service / server (VPS, Web Hosting etc.)

* Web Server Name: Apache

* [ ] Shared Host

## Expected Behavior (Not required for Request)

Tempest script to be running and to be clean from mallware.

## Current Behavior (Not required for Request)

Tempest script running successfully, but infect devices with mallware - Bitcoin miner.

## Steps to Reproduce (Not required for Request/Question)

Download the tempest.php to your webserver public_html directory. Scan this directory with antivirus software for Linux.

**Comment by K-vanc** [comment]
Hi,

I believe you are getting some false positive or someone reported tempest.php file as dangerous or you have another issue and also tempest.php file is being quarantined together with that problem but there is no malware or miner or etc in php file.

tempest.php file is not encrypted but it is only shuffled(made it hard to read) to hide my siteconfig protection. All variable names, all strings, all functions, all other things are staying as it is as in my original file and searchable with notepad. Anyway, it is always upto users to decide what is safe and what is not safe. You can try your luck with fully closed source .exe grabber alternatives

**Comment by K-vanc** [comment]
in last 8-10 days, someone is continuesly scanning my repo with a cyber threat website. I can see it on visitors tab. Maybe what you get is related with that one, As I said if someone flagged it as dangerous, we will get false positive with the tools that are using same database

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/c89e0607-beee-4da9-8e4d-dde1d67d2f78)

**Comment by K-vanc** [comment]
https://www.virustotal.com/gui/file/c68a5426d1d7a7fbe9f0ac7ccb1d7d883efd4190f63aa903e85cce4f2ecc877b/detection

**Comment by Toei79** [comment]
i dont think some like that can be in such a small file .  i dont see how can do that, if it was a windows exe with several stuff. but no

**Comment by K-vanc** [comment]
Hi;

I am closing the issue since everyone is aware about the virus now after 1 week of listing 😄

**Comment by Toei79** [comment]
I want to add something here in case anyone comes and reads this, I have been a Tempest user since the beginning, I had never had any kind of virus detection, but I did get what you saw, in my case I think it was something else, and what Google is saying is a false positive. It is more common than you might think, there are even certain malware programs that detect it while other antivirus programs do not detect anything in other programs. It is something normal that sometimes happens.
