### ISSUE TITLE
Site config request : for Indian Folder

### ISSUE THREAD

**Issue by dbmtech** [K-vanc/Tempest-EPG-Generator#14]
Hey K-Vanc

I want site config for following sites in India's folder

1. https://www.dishtv.in/channelguide
2. jio.com

 They have lot of  channels which aren't available in category India site config. above requested site EPG are available in webgrab+. I'm new here and try Tempset-EPG-Generator, output is great for me. I shall be grateful to you if you add above requested site config in India folder.

Thanks

**Comment by K-vanc** [comment]
Hi and thanks for using Tempest. 

I did dishtv long time ago for webgrab. I will add for Tempest repo as well as soon as I have time. 

For jio, there is no epg data on their website. I remember as wg was using their android application over a member's credential who has subscription. Also I remember as it was not needing user's credential for epg url calls so was just needed to pass login page and see epg urls. Currently, I cannot do it since i dont have any subscription or someone who is willing to share his credentials.

**Comment by dbmtech** [comment]
Thanks for quick response.
Take your time for dishtv repo.
I have JIO subscription and  I can share my jio credentials. It will be wonderful to see JIO site config.

**Comment by K-vanc** [comment]
Ok. I will let you know when I have time for jio since I need some other debugging tools to be set up for it then you can send me credentials by mail

**Comment by dbmtech** [comment]
Ok, thanks

**Comment by K-vanc** [comment]
Hi, I added 2 version of dishtv as English and Hindi(if available). Please check how good they are working then I will close the issue :)

**Comment by dbmtech** [comment]
Thanks

Its working good but both (English and Hindi) have same output. I think Hindi is not available.  dishtv as English is sufficient.

**Comment by K-vanc** [comment]
Not every channel and show has hindi data so i set as to grab english if not available. Usually cinema channels has information in hindi. I am closing the issue. Tomorrow will be my off day so try to have a look jio. You can send details to 
tempestepg@gmail.com

**Comment by dbmtech** [comment]
ok

**Comment by K-vanc** [comment]
hi. Jio has been added to India folder as English and Hindi options

**Comment by dbmtech** [comment]
Jio Site Config In Indian Folder is not working, Kindly Check.

**Comment by K-vanc** [comment]
Updated

**Comment by dbmtech** [comment]
Thanks but [ENC][EX]jio.com[en]_0.siteconfig still not working.
[ENC][EX]jio.com[hi]_0.siteconfig working.

**Comment by dbmtech** [comment]
Yeah I tried with latest updated site config zip

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dbmtech** [comment]
sorry I was talking about channel generation, its grabbing no channel previously. Now OK Thanks

**Comment by nabendu1** [comment]
@K-vanc thank you for this amazing tool . I am new to it and can confirm the Jio EPG generator is working fine. However, 

I have one query that currently the tempest configurator can only extract the future dated EPG using <timespan> option in feature tempest.config.xml but it does not allow backdated EPG extraction . Jio allows a catchup of previous 7 days data . I tried editing the tempest.config.xml  <timespan> parameter to negative days as well but it fails. I was looking at backdated EPG generation to use the catchup functionality on a Kodi extension. 

I did not create a new issue / feature request as I am new to the Tempest EPG Generator and probably a way exists already to do that which I was not able to figure out

**Comment by K-vanc** [comment]
Hi '[nabendu1](https://github.com/nabendu1). Tempest does not have grabbing feature for previous day. Even if you grab them, they will be removed by its date filter but Tempest supports catch-up service regardless of source is supporting it or not. To activate it, you need to enable "Fusion" option from your Tempest configuration file and need to set "Fusion level" as per your need. It means previous days to be stored and supports up to 15days;

![image](https://user-images.githubusercontent.com/97025515/223618181-3f85ea77-1ec6-4c9c-bb99-6bc6ebd12b8b.png)

When you start daily grabbing, shows from previous days will be accumulated and stored in your resulting epg xml file. Again, please note that it is not grabbing from previous days but storing of previous days and needs time and periodical runs to cover all your catch-up range. As an example, if you freshly grab today 3 days of epg data with fusion level 5(means upto 5days of previous days data allowed), there will be only 3 days(today + next 2 days) data in your xml file. When you run same config again tomorrow, you will have freshly generated new 3 days + yesterday's data. When you run it again day after tomorrow, you will have new 3 days + 2previous day's and it will continue to accumulate like this till it reach fusion limit.

**Comment by nabendu1** [comment]
@K-vanc  thank you for the information . Also could you check the below the existing channel list in site_config channel.xml is 981 channels but the latest one is somewhere around 1015 channel . Is it possible for you to update the site config xml using the below 

https://jiotv.data.cdn.jio.com/apis/v3.0/getMobileChannelList/get/?langId=6&os=android&devicetype=phone&usertype=tvYR7NSNn7rymo3F&version=285

**Comment by K-vanc** [comment]
I will update @nabendu1 . I edited your message since i think it was containing some your personnel data

**Comment by K-vanc** [comment]
It is updated
