### ISSUE TITLE
China cntv.cn epg 

### ISSUE THREAD

**Issue by Yumega** [K-vanc/Tempest-EPG-Generator#141]
## Issue Type

Please choose your issue type

* [✓ ] Request

Nice developer,All things work fine,the current China epg is limited.
introduce a best China epg with almost all popular channels

http://cbox.cntv.cn/epg/welchn.shtml

http://cbox.cntv.cn/epg/initchn.shtml

Thank you in advance😇

**Comment by K-vanc** [comment]
You have asked enough I think

**Comment by K-vanc** [comment]
> > You have asked enough I think
> 
> Okay, I will stop using it, Delete it from my system.

Up to you
