### ISSUE TITLE
[REQUEST] OLYMPIA 2024 EPG 

### ISSUE THREAD

**Issue by cyb3rgh05t** [K-vanc/Tempest-EPG-Generator#143]
hi :)

is it possible to get EPG for Olympia?

https://www.ardmediathek.de/sport-olympia-paris

thanks

**Comment by K-vanc** [comment]
Hi, i checked website but source is not suitable for xmltv conversion. There is only start time of events without any date/stop time and the worst part is  events are starting at the same time. These combination means cannot be grabbed properly. If you have any alternative, i can check that one also but for this, sorry.

**Comment by cyb3rgh05t** [comment]
thanks for looking at, but i dont have any alternative at the moment

**Comment by K-vanc** [comment]
Welcome. I added siteconfig for main website(not Olympia) into repo
