### ISSUE TITLE
New tempest.php version does not run.

### ISSUE THREAD

**Issue by misar1** [K-vanc/Tempest-EPG-Generator#144]
The new (August 2024) configuration files work OK with last year's tempest.php (created 06/09/2023). The latest tempest.php version created 02/08/2024 does not run. The php version is 8.2.3, running on Windows 11.

**Comment by K-vanc** [comment]
Hi, can you explain what you mean by not working? Configuration file is just an xml file with your selected channels and some user setttings. It is not running file. Also instead of dates, if you write tempest versions as latest(2.0.0.0) and old one as 1.5.3.0 example, it will be easier for me to understand.

As I said this is not a running file but it is being red by Tempest during run time. If there is a corruption on xml structure, you will get a screen message about problem

**Comment by K-vanc** [comment]
if you attach also configuration file, I can check it

**Comment by misar1** [comment]
The version of tempest.php which works is rv1.5.3. Here are copies of both files - I renamed the 2024 version so they both go in the same zip. Not working with the new tempest.php means nothing happens when I run my usual command line (from D:\tempest) such as:
php d:/tempest/tempest.php engine=Generate tempconfig=tvguideRT.config.xml

[tempest.zip](https://github.com/user-attachments/files/16487688/tempest.zip)

**Comment by misar1** [comment]
Hi, I just noticed another problem with the xml guides I downloaded with the 2024 configuration files using the 2023 tempest.php. They appeared to be normal but on closer inspection no programmes have the <desc lang="en"> field. This applies to both Radio  Times and Sky.

My apologies if I have missed the obvious but I am running exactly the same scripts that worked last week before your August update.

**Comment by K-vanc** [comment]
> The version of tempest.php which works is rv1.5.3. Here are copies of both files - I renamed the 2024 version so they both go in the same zip. Not working with the new tempest.php means nothing happens when I run my usual command line (from D:\tempest) such as:
> php d:/tempest/tempest.php engine=Generate tempconfig=tvguideRT.config.xml
> 
> [tempest.zip](https://github.com/user-attachments/files/16487688/tempest.zip)
> 

No it is my fault, only posted on general thread and kept it there for 1 week as announcement, also mentioned on change log of github repo but seems never enough.. 😀

https://github.com/K-vanc/Tempest-EPG-Generator/issues/17#issuecomment-2089903182

**Comment by K-vanc** [comment]
> Hi, I just noticed another problem with the xml guides I downloaded with the 2024 configuration files using the 2023 tempest.php. They appeared to be normal but on closer inspection no programmes have the *desc lang="en"* field. This applies to both Radio  Times and Sky.
> 
> My apologies if I have missed the obvious but I am running exactly the same scripts that worked last week before your August update.
> 

For this one can you try again with new version and new commands. If still exists, tell me siteconfig name because it is not related with tempest

**Comment by K-vanc** [comment]
I justed tested 1 channel from radiotimes and lang attribute is there in desc![Screenshot_20240804_173941_Chrome.jpg](https://github.com/user-attachments/assets/e477bfdf-7c2d-4472-b0dd-c541d1cb8acd)

**Comment by misar1** [comment]
Hi, I still have a problem which is probably me missing the obvious.

I have now using Ver 2 of tempest.php with the new format configuration file which it generates (see attachment). It runs correctly from the command line using the revised format on p49 of the latest Wiki version (see attachment). I expected an EPG.xml file to be in the Tempest folder from which I ran the command line but I cannot find it there or anywhere else.

[Tempest CLI.zip](https://github.com/user-attachments/files/16488151/Tempest.CLI.zip)

**Comment by K-vanc** [comment]
I see 😀 that you are not reading any news or updating tempest for ages 😀 

As of 1.6, (i guess, not remember cleraly) it was a milestone update for docker integration, epg and log folders created and files moved into them 😀 

https://github.com/K-vanc/Tempest-EPG-Generator/issues/17#issuecomment-1762748587

And I will give you a secret. During your absence, we started to merge multiple xml files into single file and gain the ability of sync(paralel) grabbing. Imagine running 5 or more tempest at the same time for generating your same xml file but 5 times faster 😀  but dont tell anyone

**Comment by misar1** [comment]
OK, I've got it. 😊
I didn't know that you use the Roadmap issue as a changelog. Thanks for the very quick replies on a Sunday. 😊

**Comment by K-vanc** [comment]
Welcome 😀 

I am announcing major changes in advance on roadmap thread to aware everyone and there are detailed explanation of changes and new features under release tab 

https://github.com/K-vanc/Tempest-EPG-Generator/releases/tag/rv2.0.0.0
