### ISSUE TITLE
Error 503 in Movistar Plus+

### ISSUE THREAD

**Issue by jasimancas** [K-vanc/Tempest-EPG-Generator#150]
## Issue Type

Please choose your issue type

* [ ] Request
* [X] Bug
* [ ] Question

## OS Details (Not required for Request)

Please choose your OS

* [ ] Windows
* [ ] Unix
* [X] Docker

Hi, Great project, I love it, I have configured it, but I have this error when I generate EPG of Movistar Plus+ (Spain).

Thanks!

![image](https://github.com/user-attachments/assets/35b7e6a0-a6b2-4fa5-979f-eca0fcfd9cfa)

**Comment by K-vanc** [comment]
Hi,

Thanks for using Tempest. Siteconfig updated, please delete old file and replace with new one.

**Comment by K-vanc** [comment]
Hi, probably the one I uploaded was still not working for you. I was trying some experimental things on encryption and noticed updated that siteconfig before fully reverting my changes.. Anyway I uploaded another version now. This should work for you and everyone else.
