### ISSUE TITLE
Question for the latest version of tempest.

### ISSUE THREAD

**Issue by devhik** [K-vanc/Tempest-EPG-Generator#151]
# Question
Does the latest version of tempest support multiple configs in one instance command:
`php tempest.php --epg config=config1 config=config2 config=configN`

As well as the xml-merge feature:
`php tempest.php --xmlmerge xml=file1 xml=file2 xml=fileN out=guide gz`

**Comment by K-vanc** [comment]
Hi;

About how to use it is clearly explained in TempestWIKI.pdf under Synchotron title. It is just matter of 3 clicks but i like your imagination about command line 😀

It is running different(or same) siteconfigs with multiple intances in the same configuration file. So not running multiple configuration file at the same time which is you dont need something special to do it as it can be done on all Windows and Unix by default with multiple calls from command line
