### ISSUE TITLE
sooka.my 

### ISSUE THREAD

**Issue by devhik** [K-vanc/Tempest-EPG-Generator#153]
The generated generates are all the same. 
![Screenshot_2024-08-29-14-00-14-185_com android chrome](https://github.com/user-attachments/assets/a93bf646-48ad-4f36-aec6-d410bcd9deba)

**Comment by K-vanc** [comment]
Hi

Siteconfig and channel list updated. Delete old channels since all channel ids are changed.

**Comment by devhik** [comment]
> Hi
> 
> Siteconfig and channel list updated. Delete old channels since all channel ids are changed.

Looks like astro config too

**Comment by K-vanc** [comment]
> > Hi
> > Siteconfig and channel list updated. Delete old channels since all channel ids are changed.
> 
> Looks like astro config too

Seems there is no change on astro except that they are ip or geo blocking now. server is refusing my request but it works when I test with a random singapore proxy
