### ISSUE TITLE
Help with command line start needed

### ISSUE THREAD

**Issue by AngusMacGyver-DE** [K-vanc/Tempest-EPG-Generator#154]
## Issue Type

Please choose your issue type

* [ ] Request
* [ ] Bug
* [x] Question

## OS Details (Not required for Request)

Please choose your OS

* [ ] Windows
* [ ] Unix
* [x] Docker

Please write your version details (PHP version is not required for Docker)

* PHP Version: ...

* Tempest Version: rv2.0.0.0-2407201314

Please write your web server name(Apache/Nginx etc.) or tick shared host if you are running on a shared host service / server (VPS, Web Hosting etc.)

* Web Server Name: ...

* [ ] Shared Host

## Expected Behavior (Not required for Request)

Please describe the behavior you are expecting

## Current Behavior (Not required for Request)

I have a the following script:
`docker exec -u root tempest_epg php /var/www/html/tempest.php --epg config=schedulesdirect1.config.xml
cp /srv/dev-disk-by-uuid-d502b8c9-5cf9-4cc5-8323-533285d5bc4e/appdata/tempest_epg/config/epg/schedulesdirect_inv.xml /srv/dev-disk-by-uuid-d502b8c9-5cf9-4cc5-8323-533285d5bc4e/appdata/tvheadend/config/data`

Unfortunately it seems to start with a "config.xml" (which is non-exsisting) and then complaines abot missing channel configuration:
`
[                   ]
[                   ]-------------------------------------
[                   ]        Tempest EPG Generator
[                   ]
[                   ]   The Most Advanced Programmable
[                   ]       GUI XMLTV EPG Generator
[                   ]     by Kivanc Altug aka "Kvanc"
[                   ]-------------------------------------
[                   ]
[30-08-2024 23:29:13] Tempest Version : rv2.0.0.0-2407201314
[30-08-2024 23:29:13] System Info : Linux 258679069b37 6.8.12-1-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.12-1 (2024-08-05T16:17Z) x86_64
[30-08-2024 23:29:13] PHP Version : 8.2.12
[30-08-2024 23:29:13] Server Info : Command Line Interface (Cli)
[30-08-2024 23:29:13] Initializing...
[30-08-2024 23:29:13] Checking required modules...
[30-08-2024 23:29:13] Guide.xml generated...
[30-08-2024 23:29:13] Grabbing started for 1 day
[       Error       ]
[30-08-2024 23:29:13] No active channel found in config.xml...
[30-08-2024 23:29:13] Operation terminated...`

![2024-08-30_234506](https://github.com/user-attachments/assets/cf27907b-1658-4d8a-9d88-8a4c61cf23c2)

I tried many notations of the "schedulesdirect1.config.xml" in the script; but none of them worked.

What do I do wrong here? And: How to do it corrently?

## Steps to Reproduce (Not required for Request/Question)

Please explain how to reproduce this issue

## Attachments (Not required for Request/Question)
Shell script:
[schedulesdirect1.txt](https://github.com/user-attachments/files/16822263/schedulesdirect1.txt)

**Comment by K-vanc** [comment]
Hi, 

In simplified command snytax, you just need to write configuration or siteconfig names without tempest file extensions so you just need to delete ".config.xml" part and it will work.

`docker exec -u root tempest_epg php /var/www/html/tempest.php --epg config=schedulesdirect1`

On your command line, Tempest is looking for a file called "schedulesdirect1.config.xml.config.xml" and when it cannot find, it is proceeding with default config file(tempest.config.xml) which seems you don't have any selected channel inside.
