### ISSUE TITLE
[REQUEST] WAIPU.TV EPG

### ISSUE THREAD

**Issue by cyb3rgh05t** [K-vanc/Tempest-EPG-Generator#155]
hi,

possible to add ```https://www.waipu.tv/``` EPG ? its a German Provider.

Thanks in advance :)

**Comment by K-vanc** [comment]
Hi;

I dont see any epg on website. Probably behind some login?? I will check more detailed tomorrow since I am away from keyboard now

**Comment by cyb3rgh05t** [comment]
i will check for login details

**Comment by cyb3rgh05t** [comment]
ok got some account. where can i send you the details?

**Comment by K-vanc** [comment]
You can send here;

tempestepg@gmail.com

I will check tomorrow. If epg fetching requires login data, i will send you private siteconfig by mail instead of adding into repo

**Comment by cyb3rgh05t** [comment]
will do thanks

**Comment by cyb3rgh05t** [comment]
email sent :) thx

**Comment by K-vanc** [comment]
Hi, normally it is using login data for epg calls but I found some alternative urls to grab without credentials and seems it is working(at least for now) so added into Germany folder as play.waipu.tv

If they block it in the future, I may need login data again to try hard way..

**Comment by cyb3rgh05t** [comment]
create thanks

**Comment by AngusMacGyver-DE** [comment]
Just an additional note on that: 
If a paid subscription for EPG - about 35 USD/Year - is ok then schedulesdirect.org also has provider waipu.tv available (at least I could find a lineup with that name there; have not tried it myself as I`m using Zattoo currently).

Schedulesdirect is getting their data directly from Gracenote, Inc. and for me data quality is okay.

**Comment by K-vanc** [comment]
> Just an additional note on that: If a paid subscription for EPG - about 35 USD/Year - is ok then schedulesdirect.org also has provider waipu.tv available (at least I could find a lineup with that name there; have not tried it myself as I`m using Zattoo currently).
> 
> Schedulesdirect is getting their data directly from Gracenote, Inc. and for me data quality is okay.

SchedulesDirect has thousands of line-ups from many countries over the world as the biggest EPG Service. As you know, Tempest is one of the approved application for SD-JSON service and has to respect their policies to keep its title.

https://schedulesdirect.org/approvedsoftware

Just a general reminder for not asking me siteconfigs from them except the one provided which works with SD subscription 😄
