### ISSUE TITLE
[REQUEST] DAZN EPG

### ISSUE THREAD

**Issue by cyb3rgh05t** [K-vanc/Tempest-EPG-Generator#156]
Hi,

possible to add different DAZN configs for different countries? like DAZN it , es, ch, de, etc? 

thanks

**Comment by K-vanc** [comment]
If you have sources, yes but as far as i know there is no epg data in dazn websites. There are only some events. It is better and easier to get them from country providers such as guidatv.sky.it for Italy, sky.de for Germany etc. 

I published only 1 dazn siteconfig for Germany but it is not official as far as i know, just 1 user found it requsted

**Comment by cyb3rgh05t** [comment]
alright thanks

**Comment by tvguideone** [comment]
> If you have sources, yes but as far as i know there is no epg data in dazn websites. There are only some events. It is better and easier to get them from country providers such as guidatv.sky.it for Italy, sky.de for Germany etc.
> 
> I published only 1 dazn siteconfig for Germany but it is not official as far as i know, just 1 user found it requsted

maybe this can help: https://epg.discovery.indazn.com/de/v3/epgWithDatesRange?country=de&languageCode=en&openBrowse=false&timeZoneOffset=420&startDate=2024-09-11&endDate=2024-09-17

https://epg.discovery.indazn.com/eu/v2/Epg?date={today.year}-{today.month:02d}-{today.day:02d}&country={country_code}&languageCode={language_code}&openBrowse=false&timeZoneOffset={time_offset}

**Comment by K-vanc** [comment]
Hi @tvguideone ,

Thanks for the links. it seems like they may work. I will check what can i do with them

Note: Urls deleted due to privacy

**Comment by K-vanc** [comment]
Added into Multi Nation folder with all available country channels which set to local language option. Thanks for your contribution @tvguideone

**Comment by tvguideone** [comment]
> Added into Multi Nation folder with all available country channels which set to local language option. Thanks for your contribution @tvguideone

Maybe you can add DAZN Linear Live Channel too

https://rail-router.discovery.indazn.com/jp/v6/Rail?platform=web&id=Livetvschedule&country=jp&languageCode=en

**Comment by K-vanc** [comment]
I will check that one too

**Comment by K-vanc** [comment]
it is also added into Multi Nation Folder as dazn[linear]
