### ISSUE TITLE
[Multi Nation] gatotv.com

### ISSUE THREAD

**Issue by devhik** [K-vanc/Tempest-EPG-Generator#158]
The schedule taken does not match the time, maybe you can fix it. Thank you

**Comment by K-vanc** [comment]
Sorry but I cannot help with this information..

If you want to get support, please fill the issue template with all the information asked and explain what is the problem for which channel and what it should be..

I cannot waste my time by trying understand what is the problem on which channel

**Comment by devhik** [comment]
I have tried the config you updated, but it reports `Stop-time conversion error found on block 1...` 
![Screenshot_2024-09-05-09-36-11-632_com android chrome](https://github.com/user-attachments/assets/e0013a3e-0a4f-42ec-9437-1f85cc63b525)

**Comment by K-vanc** [comment]
![image](https://github.com/user-attachments/assets/512c7be5-2448-4561-98ca-5e82d55585c7)

![image](https://github.com/user-attachments/assets/e1d816af-2d91-4415-98ee-e9d956fd2a60)
