### ISSUE TITLE
Its possible add option to add a logo to "x"  channel

### ISSUE THREAD

**Issue by Toei79** [K-vanc/Tempest-EPG-Generator#16]
Many times epgs comes without logos some channels ,

Its possible like add a link for the logo just copy paste on a channel? 

Idk maybe option its there

Maybe in the channel indexer
Thanks

**Comment by K-vanc** [comment]
Currently you can do it only for unlocked siteconfigs with ||#add# command described in TempestWIKI.pdf.

For locked siteconfigs, i am working on a new command to allow users add their own logo urls. It is the only remaining item in my list for releasing rv1.4.3.

%70 of code is done but need to align for cyclone option. It seems I will not be able to finish it before going vacation So 2 weeks later

**Comment by Toei79** [comment]
I will check manual thanks , I use tivimate but don't have option to do manually but its lot better through  epg

Many channels are no logo really useful

Have good vacation! :)

**Comment by K-vanc** [comment]
Thanks. Btw which siteconfig you are mentioning? Just very small amount of siteconfigs I made, has no channel logo

**Comment by Toei79** [comment]
> Thanks. I already created 1 issue as roadmap and added this there. So I will close this one.
> 
> Btw which siteconfig you are mentioning? Just very small amount of siteconfigs I made, has no channel logo

Usa ones there its many without logos 
They have like maybe 75%  logos . I need check tonight  but ones with many sites in one siti comes without

Here we get like 18.1  18.2. 18.3...18.9 , those subchannels suffer from no right logo maybe 50%  of those, they get a symbolic one, but its issue on many or all guides 

Tvguide its amazing because  many countries , but at least in my area they offer guide for so e channels already gone, there its one that gone like 6 years ago and other like 12 years , ota channels.

There its zap2it its more accurate  for ota plus you get descriptions

I'm thinking meanwhile  I can do a script to add logos maybe  
Idk too much about this but did one for radios [one repeating same guide and just changi g the dates] so maybe I can  do for the logos one meanwhile.

**Comment by K-vanc** [comment]
Oh, i see. Some of those websites has no logo and only channel names. Zap2it is already in my to-do list. Try to stand for a few weeks then you will just add logo url from Configurator for channels you want :)

**Comment by K-vanc** [comment]
Hi @Toei79 . zap2it added to USA folder with updated instruction for channel creation. Website is geo-blocked so you will need to suitable VPN or ip address

**Comment by Toei79** [comment]
> Hi @Toei79 . zap2it added to USA folder with updated instruction for channel creation. Website is geo-blocked so you will need to suitable VPN or ip address

Hi thanks for the amazing job :)

Im in usa i dont get block thing fortunely yet
