### ISSUE TITLE
Req: Add Description - USA /[ENC][EX]tvlistings.zap2it.com_0.siteconfig.php

### ISSUE THREAD

**Issue by petediddy2023** [K-vanc/Tempest-EPG-Generator#161]
## Issue Type

Please choose your issue type

* [X] Request
* [ ] Bug
* [ ] Broken Siteconfig
* [ ] Question

## OS Details (Not required for Request)

Please choose your OS

* [ ] Windows
* [ ] Unix
* [X] Docker

Please write your version details (PHP version is not required for Docker)

* PHP Version: ...

* Tempest Version: ...

Please write your web server name(Apache/Nginx etc.) for local servers, tick docker for docker image or tick shared host if you are running on a shared host service / server (VPS, Web Hosting etc.)

* Web Server Name: ...
* [x] Docker
* [ ] Shared Host

Requesting to have description added to xml output of [ENC][EX]tvlistings.zap2it.com_0.siteconfig.php.

Thank you!

**Comment by Toei79** [comment]
i guess its there you need change something.  where you add channels.  tempest configurator. there.

**Comment by Toei79** [comment]
![image](https://github.com/user-attachments/assets/4a3713c9-69ed-4463-83c4-ab74d4e211b4)
this its mine.  i get descriptions.  i use zap2it.

**Comment by K-vanc** [comment]
Hi @petediddy2023 

There is no change on website and you should able to grab descriptions without any problem if you are using updated Tempest. Current version is Rv2.1.0.0. You can update Tempest from command line or by clicking Tempest Updater from GUI. Default docker version Rv1.6.0.0 and the problem you mention is fixed as of 1.6.1.1;

https://github.com/K-vanc/Tempest-EPG-Generator/releases/tag/rv1.6.1.1
