### ISSUE TITLE
optussport

### ISSUE THREAD

**Issue by tvguideone** [K-vanc/Tempest-EPG-Generator#166]
Hhi, I found a pretty complete epg data page to pull from, rather than the current config, maybe you could add it...

https://sport.optus.com.au/api/metadata/editorials/v2/home_live_matches/web

**Comment by K-vanc** [comment]
Sorry but this is not even close to the thing called as complete epg. It is only an url for live events and jumping over days for the next live event.

I will not update or create a siteconfig for this. Existing siteconfig is unlocked so if you want, you can modify it based on your needs

**Comment by devhik** [comment]
> Sorry but this is not even close to the thing called as complete epg. It is only an url for live events and jumping over days for the next live event.
> 
> I will not update or create a siteconfig for this. Existing siteconfig is unlocked so if you want, you can modify it based on your needs

Yes, most of the Optus channels are for live events.

**Comment by devhik** [comment]
`Channel list can be taken from here.`
https://sport.optus.com.au/api/metadata/editorials/v2/home_live_matches/web

`Retrieving program data`
https://static.sport.optus.com.au/api/metadata/assets/v2/os80728/web

`Example`
os80728 = Optus Sport 7
os81316 = Optus Sport 11

**Comment by K-vanc** [comment]
I have updated siteconfig for channel creation with live event url. Now there are 24 channels..

> Retrieving program data
https://static.sport.optus.com.au/api/metadata/assets/v2/os80728/web

this is not epg url, it is show detail..

As I already said above, I am done with it. If you want, modify your own copy
