### ISSUE TITLE
Help with Processed data

### ISSUE THREAD

**Issue by NHKRoku** [K-vanc/Tempest-EPG-Generator#169]
Hi,I'm getting trouble with processed data on [SG] mewatch'siteconfig,on image link always add syntax "amp;" although on the real data doesn't have it
It like this:
Original data:["images":{"logo":"https://prod98.togglestatic.com/shain/v1/dataservice/ResizeImage/$value?Format='png'&Quality=85&ImageId='3769261'&EntityType='LinearSchedule'&EntityId='2e1af195-a745-47ea-a083-bfde2ebc0832'&Width=284&Height=106","wallpaper":"https://prod98.togglestatic.com/shain/v1/dataservice/ResizeImage/$value?Format='jpg'&Quality=85&ImageId='8238401'&EntityType='LinearSchedule'&EntityId='2e1af195-a745-47ea-a083-bfde2ebc0832'&Width=1280&Height=720",]
Tempest generated data:src="https://prod98.togglestatic.com/shain/v1/dataservice/ResizeImage/$value?Format='jpg'&amp;Quality=85&amp;ImageId='8238401'&amp;EntityType='LinearSchedule'&amp;EntityId='2e1af195-a745-47ea-a083-bfde2ebc0832'&amp;Width=1280&amp;Height=720"]
I'm thinking that can another command can remove them?
Looking forward to hearing from you.

**Comment by K-vanc** [comment]
They are escape chars and MUST BE ENCODED LIKE THAT.. otherwise your xml file will be corrupted..

https://www.geeksforgeeks.org/how-to-escape-characters-in-xml/

Find a better player if the one you use cannot decode escape chars, there is nothing i can do
