### ISSUE TITLE
Generate Custom EPG / Listings for 24/7 Channel

### ISSUE THREAD

**Issue by ouija** [K-vanc/Tempest-EPG-Generator#170]
## Issue Type

Please choose your issue type

* [x ] Request
* [ ] Bug
* [ ] Broken Siteconfig
* [ ] Question

Hey there,

New to using this software, and curious if there is a way to create a custom site_config / epg listing for a 24/7 News Channel that I have that I'd just like to have say "24/7 News" in the EPG at all times.

I know how I could add this into the `Guide.xml` directly, but just curious if you could possibly provide a quick site_config that might have this capability or somehow point me in the right direction _(if/when you have time!)_

EDIT:  I suppose I could get by with using the _XML Merger_ capability and merge in my own custom .xml listing, but was trying to avoid having to run a secondary php call when generating the EPG....

Thanks!

**Comment by K-vanc** [comment]
Hi;

There are weekly and daily dummy siteconfigs for custom channel epg. All you need to do is modifying source files for shows and add channel(s) into your configuration. It will be grabbed together with normal siteconfigs so no need to use xml merger(if you dont really want to use it)

https://github.com/K-vanc/Tempest-EPG-Generator/tree/main/Siteconfigs/Miscellaneous

Check info file there for instructions with pictures
