### ISSUE TITLE
Set timezone / offset per channel?

### ISSUE THREAD

**Issue by ouija** [K-vanc/Tempest-EPG-Generator#172]
Hey,

Been using your script to generate a beauty of an EPG!   One question I had is if it is possible to set a timezone/offset per `<channel>` or if best to just do this with custom site_config?  _(which is what I've currently done)_

Thanks!

**Comment by K-vanc** [comment]
Hi;

||#offset# command explained in TempestWIKI.pdf. You can add this command to end of xmltv_id value from Configurator for the channel(s) you want to change show times. It is working as minutes and can be + or - ;

![image](https://github.com/user-attachments/assets/f6358ebc-45cf-400c-907b-a4fe5f80871f)

This will keep the timezone same but let you adjust show times of specific channel(s). If you want to change timezone, then this is completely different thing. You may use time-converter setting from Configurator but this will change/adjust timezone of all channels in resulting xml file;

![image](https://github.com/user-attachments/assets/31c76dc1-a72c-4a7a-8bf0-1b0d05bd3c7d)

And last option for changing timezone is editing it from siteconfig file. This value set by me and it should be correct for all siteconfigs unless they did some change after me. In this case you can edit if siteconfig unlocked or open an issue as wrong timezone if siteconfig encrypted so I will check
