### ISSUE TITLE
Is "synchrotron" using Node.js?

### ISSUE THREAD

**Issue by ouija** [K-vanc/Tempest-EPG-Generator#173]
Not an issue, just a question after discovering "synchrotron" mode today -- is this using Node.js to perform this?  Just curious about it, since I did notice an instance of this running, but didn't see any mention of such in the documentation.

**Comment by K-vanc** [comment]
Hi, 

Node.js or any other javascript library(except jquery for form events) are not part of Tempest. Synchrotron module has been purely coded on php. It is converting running first script into manager mode and allowing it to run new Tempest instances via command line and periodically checking their working status with several nested loops

**Comment by K-vanc** [comment]
if you wondered how I am running multiple instances, it is done by php's "popen" function combined with tempest's --epg command then generated files are being combined with xmlmerge module of Tempest by manager script. So it is a self supported solution 😄

**Comment by ouija** [comment]
Ahh okay, perfect!   I got confused seeing Node.js running on this VM I was testing with, but I believe it was running due to Visual Studio Code (which I was using to remotely connect to the machine) but I wanted to double-check.   Apologies for the confusion!

**Comment by K-vanc** [comment]
No problem
