### ISSUE TITLE
Site config source for either epgshare01 or i.mjh.nz

### ISSUE THREAD

**Issue by ouija** [K-vanc/Tempest-EPG-Generator#174]
Just curious if you might be able to share the unencrypted source files for either i.mjh.nz or epgshare01?

I'd like to build a site_config similar to these, and having the source files to reference would be a huge help!   I could provide email if you'd prefer to share that way (if at all).

Thanks.

**Comment by K-vanc** [comment]
Hi, sorry but whatever encrypted is done so by a purpose. There are still plenty of unlocked siteconfigs which you may use as reference in the repo. For example, all Italy siteconfigs are always unlocked from the simplest to most complicated ones.
