### ISSUE TITLE
tvguide USA siteconfig no longer collecting

### ISSUE THREAD

**Issue by goldengate2121** [K-vanc/Tempest-EPG-Generator#175]
## Issue Type

Please choose your issue type

* [ ] Request
* [ ] Bug
* [X ] Broken Siteconfig
* [ ] Question

## OS Details (Not required for Request)

Please choose your OS

* [ ] Windows
* [X ] Unix
* [ ] Docker

Please write your version details (PHP version is not required for Docker)

* PHP Version: ...PHP 8.2.24

* Tempest Version: ...[v2.2.0.0]

Please write your web server name(Apache/Nginx etc.) for local servers, tick docker for docker image or tick shared host if you are running on a shared host service / server (VPS, Web Hosting etc.)

* Web Server Name: ...Apache
* [ ] Docker
* [ ] Shared Host

## Expected Behavior (Not required for Request)

Be able to collect EPG with the tvguide siteconfig and to be able to generate channels.

## Current Behavior (Not required for Request)

The tvguide for USA started returning 403 errors when collecting EPG. I tried generating a new channels. When I enter a zip code, I get no channels block found. I tried many different zip codes and they all say no channel blocks found. I went to the tvguide website and they are still displaying guide data.

Please describe the current behavior...

## Steps to Reproduce (Not required for Request/Question)

Go to Channel Generator and select the tvguide choice and enter a zip code it will return no channel blocks found.

Please explain how to reproduce this issue...

## Attachments (Not required for Request/Question)

Please attach your log(s), generated xml file(s), configuration.xml file(s) and/or screenshot(s) which are showing the problem...

**Comment by K-vanc** [comment]
Hi;

Both US and Multi versions were updated
