### ISSUE TITLE
ESPN + guide data

### ISSUE THREAD

**Issue by K-vanc** [K-vanc/Tempest-EPG-Generator#177]
### Discussed in https://github.com/K-vanc/Tempest-EPG-Generator/discussions/176

<div type='discussions-op-text'>

<sup>Originally posted by **goldengate2121** November 14, 2024</sup>
Is it possible to build a siteconfig and channel file for ESPN+. Looks like IPTV Boss has it but I don't know where they pull the data from.</div>

**Comment by K-vanc** [comment]
Hi, 

for requests, you need to provide me an url of working epg website/source of this channel otherwise it is being a wish instead of
request. I made a Quick check on Google but there is nothing can be used as a epg source. Maybe they are pulling from some main epg providers such as schedulesdirect or other usa network providers. If you dont know a source, you may try ur luck by checking US or Multi Nation folder siteconfigs. Some of them creating channel lists with zip codes and may have that channel.

**Comment by goldengate2121** [comment]
Hi,

I don't believe they are based on zip code but I will look at the multi-national site to see if any match. Here is where the guide data is displayed. The link is for Friday (15/11) as an example.

https://www.espn.com/watch/schedule/_/type/upcoming/channel/ESPN_PLUS/startDate/20241115

**Comment by K-vanc** [comment]
I have already prepared one siteconfig but not yet finished. Probably i will share on Saturday. There is only 1 website but they are displaying events instead of epg so it will work but you will get only the first displayed event for the start time clashing events.

**Comment by goldengate2121** [comment]
They are actually separate channels for each show. So, ESPN+ 1 - 4PM Show 1, ESPN+ 2 - 4PM Show 2, etc.

**Comment by K-vanc** [comment]
We are not talking about the same thing because we are not looking into the same thing. Anyway as i said just be patient till Saturday. I will add channel logos as only remaining thing

**Comment by K-vanc** [comment]
Hi;

espn siteconfig added into Multi Nation folder.
