### ISSUE TITLE
run from pc?

### ISSUE THREAD

**Issue by ovladuk** [K-vanc/Tempest-EPG-Generator#18]
can this be run straight from the a pc? if so how?

**Comment by K-vanc** [comment]
Hi. if you mean something like double-click as "run straight from a pc", no it is not. Tempest is a all-in-one php file and to run php, you need to server but servers are very easy to install and use. Based on your question, I guess, you are a windows user so I suggest you to download XAMPP which is very simple for beginners and you can install and start using just with few clicks. I put link of an example youtube video 

https://www.youtube.com/watch?v=jLqBiSDNXO0

When it is done, just copy-paste tempest.php into root folder and finish. How to use siteconfigs are already explained here;

https://github.com/K-vanc/Tempest-EPG-Generator/tree/main/Siteconfigs/0_How%20to%20use

In the future, I will add my own guides here about how to setup and use

**Comment by ovladuk** [comment]
> Hi. if you mean something like double-click as "run straight from a pc", no it is not. Tempest is a all-in-one php file and to run php, you need to server but servers are very easy to install and use. Based on your question, I guess, you are a windows user so I suggest you to download XAMPP which is very simple for beginners and you can install and start using just with few clicks. I put link of an example youtube video
> 
> https://www.youtube.com/watch?v=jLqBiSDNXO0
> 
> When it is done, just copy-paste tempest.php into root folder and finish. How to use siteconfigs are already explained here;
> 
> https://github.com/K-vanc/Tempest-EPG-Generator/tree/main/Siteconfigs/0_How%20to%20use
> 
> In the future, I will add my own guides here about how to setup and use

thanks! i only just got around to doing this properly but it was actually extremely simple thanks! got my sky config edited and generating my epg! very happy!

**Comment by K-vanc** [comment]
Good to hear, enjoy Tempest.
