### ISSUE TITLE
Siteconfig only grab past epg, without current and upcoming epg

### ISSUE THREAD

**Issue by RyanRiz** [K-vanc/Tempest-EPG-Generator#24]
Site: Indihometv.com
Siteconfigs: indihometv.com_0.siteconfig.php
Debugged Channel: NET.

So currently I try to grab epg from indihometv.com site with tempest, and it's working. After that, I try to put in on my iptv player, but it not showing any epg. So I got confused here. Then, I try to debugging siteconfig and compare epg with origin site. Apparently the siteconfig only grab past epg, and not current and upcoming epg. Can you help me out?

I attach some screenshot if it needed:
Screenshot epg from original site:
![Screenshot from 2023-03-29 19-12-20](https://user-images.githubusercontent.com/97774442/228531861-6fa0e7db-16ad-42bb-bff7-19663d418ea2.png)
![Screenshot from 2023-03-29 19-15-06](https://user-images.githubusercontent.com/97774442/228532250-bf4c00af-30ea-4bb1-afb9-59704d32831e.png)

Screenshot epg from siteconfig debugger:
![Screenshot from 2023-03-29 19-12-36](https://user-images.githubusercontent.com/97774442/228531878-192bb64b-0b27-4840-8d18-6b6fee1cf2e6.png)

**Comment by K-vanc** [comment]
Hi and thanks for using Tempest.

Sorry for my late reply. I was away from pc and I still am but I was able to check problem you mentioned from my mobile. This time calculation may be abit confusing so I will try to explain step-by-step. First of all, that siteconfig has only 1 day of available data and it is always today. Second thing, i am using unix timestamp for calculation show times on that siteconfig and timestamps also contain date information. If show is belongs to previous day, Tempest will automaticly discard it based on your local time settings. Now, I will mention where is timestamp and it is converted to what. I tested same channel you mentioned(net) and let's check first show(github is not currently allowing me paste screenshot so I will copy/paste);

[1] => href="https://www.indihometv.com/tvod/net/1680024600/1680029880/18304926/makan-enak"class="d-flex align-items-center schedule-item active"><span class="replay"></span><p>00:30 - 01:58</p> <b>Makan Enak</b>

In this block, start time is 00:30 without any date so it must be today as 2023-03-29 00:30 +0700(Indonesia Time as +0700) but I am using hidden timestamp there as show time which is "1680024600". If you convert this string into human readible time, it will be 2023-03-28 17:30 +0000(unix timestamps are always UTC as +0000). Now it looks like It is yesterday's show as you mentioned, correct??

But actually These 2 dates are equal when their offset's are aligned;

2023-03-28 17:30 +0000 <=> 2023-03-29 00:30 +0700

So Tempest's calculated date is correct as below;

Start Time : 

[1] => 20230328173000 +0000


At this point, problem is related with your iptv player. Even today, Still there are tons of iptv players which cannot properly calculate different time offsets. For example Kodi takes everything as +0000 for years regardless of set offset in xml file so if you have several time offsets on epg file, it all will be a mess. To avoid this, Tempest has a built-in time converter. If you set it, all show times will be recalculated as per defined timezone or offset and resulting file will have only 1 offset. You can try it by setting "Time Converter" as  

Asia/Jakarta

On Tempest Configurator under File Configuration tab. When you rerun grabbing, all shows will be recalculated with +0700 offset. I hope this will be enough to solve your problem

**Comment by K-vanc** [comment]
While checking website on my pc, I have noticed show structure is changing when a show is passed by time and noticed that siteconfig is missing some shows so I updated. It is working without timestamp now(because not exists for upcoming shows) and using only start/stop hour with Asia/Jakarta time offset. Please redownload and check again. Maybe it was related with your problem

**Comment by K-vanc** [comment]
I think this is absolutely what you asked by saying past day epg. it is not past day epg, same day but completed shows epg. When I made this siteconfig, most of the shows was completed and I didnt notice structure is different and changing for completed and upcoming shows. Thats why it was not listed on your iptv player. Now updated siteconfig will download both started and not yet started shows so you will be able to see all without any extra setting.

**Comment by RyanRiz** [comment]
Yes, that's what I meant. Sorry for my bad language, it's working very well right now. Btw I'm fastening too, so Happy Ramadan for you brother.  :smile:

**Comment by RyanRiz** [comment]
And I noticed that only few channel was generated from siteconfig. So I did experiment adding channel site id manually from other channel xml source like webgrab, and it works very good. It can grab epg up to 134 channel.

Screenshot:
![image](https://user-images.githubusercontent.com/97774442/228758979-0a5c424b-a31f-47cb-bc46-a6623821f8f4.png)

**Comment by K-vanc** [comment]
Done! Now generating 139 channels. Please redownload updated

**Comment by RyanRiz** [comment]
Thank you so much! Since all complete I will close this issue, thanks for helping me out :smiley:

**Comment by RyanRiz** [comment]
Site: Indihometv.com
Siteconfigs: indihometv.com_0.siteconfig.php
Hi again. Sorry to reopen this issue since it's probably still related.

I got into another problem again. I try my best to explain it.
So, It's the middle of the night, the day is already passed. Probably about 01:00 AM (Jakarta Time).

Original site has alredy renew epg for today (March 31). I tried to renew epg by generating new epg. But, since the previous day (March 30) had some epg left, tempest only grab that left over epg from previous day (March 30) and ignore today new epg (March 31). Are I supposed to generate it in certain time to get the lates epg? Since it's only grab 1 day epg.

Today (March 31) latest epg it's still show when I debugging siteconfig:

**Comment by K-vanc** [comment]
Hi. I understood well but actually it is not an issue. When you run that siteconfig, Tempest is creating a date string based on your machine's time setting and capturing block starting with this date string. As example, currently my time is almost 22:00 and date is still 30-03-2023. So when I run that siteconfig, Tempest is first calculating my date as 2023-03-30 and looking website's source to find block which starts with this date. Then after another Tempest feature is filtering shows till the next day 03:00 am as overflowing shows. Now, most of the shows are already over and only 2 shows are remained from early in next day as blow picture which is completely ok as per my design :)

![Screenshot_20230330-213939_Chrome.jpg](https://user-images.githubusercontent.com/97025515/228935076-7f102f35-72ff-45a7-b7f9-2126337f96cb.jpg)

Anyway, if you want to capture all existing shows in any time, you can modify siteconfig on Siteconfig Editor by choosing indihometv siteconfig and set "Mazimim Days" as 2 under Site Options tab and save.

![Screenshot_20230330-215233_Chrome.jpg](https://user-images.githubusercontent.com/97025515/228935870-4d373fa7-898a-4765-b259-2e1cde4831b7.jpg)

Now when you grab for 2 days, it will capture all existing shows

![Screenshot_20230330-215747_Chrome.jpg](https://user-images.githubusercontent.com/97025515/228936998-4d01948f-5122-476f-a908-bfc2e8d70e72.jpg)

**Comment by RyanRiz** [comment]
Thank you for your response, I understand it very well.

I tried to set "Maximum Days" as 2.1 just like you said. But when I try generate it, it's always generate only for 1 day
![Screenshot_2023-03-31-03-23-14-229_com android chrome](https://user-images.githubusercontent.com/97774442/228942465-67c07989-fc64-47e3-af44-b927841d9811.jpg)
![Screenshot_2023-03-31-03-21-48-158-edit_com android chrome](https://user-images.githubusercontent.com/97774442/228942480-3ec294b9-0d85-417f-8724-89d5eb15ad3f.jpg)

**Comment by K-vanc** [comment]
Yes because you are still requesting  1 day only :) Both in Debugger and in your Tempest Configuration file, you need to increase timespan value for 2 days request.

![Screenshot_20230330-223401_Chrome.jpg](https://user-images.githubusercontent.com/97025515/228944676-cae517ff-512e-4014-bffc-c81dcc7c63c7.jpg)

**Comment by RyanRiz** [comment]
Oh you were right, I didn't know I supposed to do that. I'm new at this, so I don't had much experience. :sweat_smile: 

Anyway It's all good now. Thanks again bro :+1:

**Comment by K-vanc** [comment]
You are welcome. I asked you to do yourself because it is pretty easy 😅 

Joke aside, I am away from pc now, and also tomorrow I will not have access So just test It and let me know if you notice any problem. I made an alternative version for 2days show grabbing on my mobile but usually not sharing before properly testing on pc. If you find any problem, i may give it to you for advance testing but probably this solution will work fine
