### ISSUE TITLE
Missing Modules

### ISSUE THREAD

**Issue by K-vanc** [K-vanc/Tempest-EPG-Generator#26]
From: @Frost2023

Hello K-vanc!
I"ve got Windows 7.

When I run Tempest-EPG I see this depiction below:

![image](https://user-images.githubusercontent.com/130272299/230757883-f29e236a-64e0-4ec1-bac1-00774c173e65.png)

And most of commands don't work. For instance, I run this command and there is no any action on my screen:

![image](https://user-images.githubusercontent.com/130272299/230758737-c166287f-e5d1-4f2b-a055-9efcefe798bd.png)

When I press generate I see this:

![image](https://user-images.githubusercontent.com/130272299/230758791-e78992a0-0d0d-4f53-a614-f997ef8037a3.png)

What have I been doing wrong when I was preparing and putting files onto my c:\ directory?

Thank you for advance for your answer!

**Comment by K-vanc** [comment]
Ok, I guess you are using php's built-in development server. Otherwise some of these modules should be enabled by default with other servers. When you extract compressed php file, you will see 2 ini(php's setting) file something like;

php.ini-production
php.ini-development

you need to rename one of them as "php.ini" (note that .ini will be file extension). So when you run your php server again, it will load that file for settings. Now, open that php.ini file with some editor and search for extension_dir . Your modules are located in /ext folder inside of your uncompressed php folder so you need to edit extension_dir with your /ext folder path. 

![image](https://user-images.githubusercontent.com/97025515/230767474-859925db-578a-4f72-8874-3f08b558504b.png)

Now, you need to enable missing modules since actually there are not missing but disabled. Go down for extensions list as below;

![image](https://user-images.githubusercontent.com/97025515/230767549-da1adb52-a3fa-4040-87b6-8c48074cc449.png)

Semicolon in front of extension name disables that module. So you need to remove " ; " in front of it then they will be enabled back. Now you can save and rerun your server. This will fix it.

Regarding that second photo, I never saw such problem if you didnt delete anything from tempest.php file or if you are not using a prehistoric web browser such as Internet Explorer. It is pure html and any modern browser which may able to render html, should show it properly.

**Comment by Frost2023** [comment]
Thank you one more time! I'll try to do this.
Could you record manual video with some minimum explanation about setup your program with some examples in it for such fool as I am?

**Comment by K-vanc** [comment]
Actually, there is no setup for Tempest. You just need to have a running php server. Good part of PHP is, it is universal and will run same on any operating system but the bad part is, it is dependant to server and each available server has their own default settings. This makes things much more complicated for unexperinced php users and it is also hard for me to understand what is the problem. I can make 10 videos about how to set 10 different server and 11th one will be a new problem so I am prefering to stay alittle away from server setup and focusing Tempest issues. For beginners, I am suggesting Xammp which is a few click installation and all required modules are enabled so just copy/paste tempest.php and you are good to go

**Comment by Frost2023** [comment]
Your explanation was quite useful for me! Your program works properly but I've got one more question. As I can see your program grabs one channel (tvtv.us) approximately for up to 50 sec. Could I make something to improve this period of time to make grabbing channels much more rapid? For example, to grab 500 channels I need wait for about 500 minutes. I guess this is too long period of time.

**Comment by K-vanc** [comment]
Tvtv.us was one of the slowest US provider for a while. I already explained its reason on below reference thread and shared 1 unofficial siteconfig with detail pages disabled if you want to try but I suggest you to use zap2it or tvguide.com which is much more useable when compared with tvtv.us

https://github.com/K-vanc/Tempest-EPG-Generator/issues/15#issuecomment-1471359495

**Comment by Frost2023** [comment]
I've got it. Thank you for all your attempts to help people like me! It's great!

**Comment by K-vanc** [comment]
You are welcome. I think your issue is resolved so I am closing the thread
