### ISSUE TITLE
Grabs data slow

### ISSUE THREAD

**Issue by stuckinthe** [K-vanc/Tempest-EPG-Generator#27]
I set 8 channels to grab 4 days worth of data mostly from ontvtonight.com. I had one grab from tvguide but it said url could not be found. Naturally, I can change this one to point to a different source. I had another from tvpassport. This grab took about 30 minutes. I would like to do more channels but if I did 100 I am looking at 5 hours. Is my number of days too long, bad sources, or this is just how long it takes?

**Comment by stuckinthe** [comment]
I thought I had searched here better before I posted.

I see you have answered this already.

https://github.com/K-vanc/Tempest-EPG-Generator/issues/26

**Comment by K-vanc** [comment]
Hi @stuckinthe. Speed of the grabbing is usually related with type of the server data, server's response speed and your connection speed. Regarding server data type, I explained how some siteconfigs are working on below comment;

https://github.com/K-vanc/Tempest-EPG-Generator/issues/15#issuecomment-1467329319

All the siteconfigs that you use, are with detail pages which means for each grabbed show, an additional webpage more has to be called.For 500 grabbed show, Tempest has to call minimum 501 webpages. It is usually considered usable when server response speed is less than 1 sec for each show but there are also some nightmare servers such as tvtv.us or tivo which page speed > 2secs even in USA. Unfortunately there is no way of changing server's data structure from my side and you need to find best and fastest alternatives based on your needs. I made some quick comparison with several siteconfigs you mentioned. 

For ontvtonight (page speed < 1s)
![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/f0ee786a-ad70-4098-810d-a04318f2ad24)

For tvguide.com (page speed < 1s)
![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/26c7fa92-f265-4f2e-a96e-99a072f41011)

For tvtv.us and tvpassport, I need vpn which currently not installed my pc but more or less you know their response speed..

You can consider some faster siteconfigs such as zap2it(no detail page/VPN or US ip required) or tvguide(with detail page but faster response speed(around 0.5 secs per show)).
