### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by TheDeatCrusher** [K-vanc/Tempest-EPG-Generator#3]
I wanna know how to get 7 days of the epg

**Comment by K-vanc** [comment]
Hi and thanks for using Tempest. Seems you have already found the answer but to explain any other user who needs same info, grabbing day can be set with timespan value in Configuration settings. "0" means today only and increases with number as today + set value so if you set "6", it will be today + following 6 days and you will have 7days epg of course if the siteconfigs you selected support that long grabbing. Usually siteconfigs support 7 or more days but some rare websites have 3 days of data or less. In this case Tempest will grab from those siteconfigs with max possible days if your timespan is higher
