### ISSUE TITLE
Filtering out style tags in titles

### ISSUE THREAD

**Issue by stuckinthe** [K-vanc/Tempest-EPG-Generator#30]
I am having an issue where I am seeing css/style tags in my titles which clips the full title. Is there a way to filter out the style tags. Seems like it happens on sporting events with tivo sources.

**Comment by K-vanc** [comment]
Hi;

I dont think that I understood well what is the problem. I randomly debug some sport channels but didnt see any css tag on title. Could you please write channel name/postal code that you are having issue and if possible some screenshot showing the problem ?

**Comment by stuckinthe** [comment]
See example of Bally Sports Detroit from the tivo source
![imgonline-com-ua-dexif7Gz8up3BbmqN](https://github.com/K-vanc/Tempest-EPG-Generator/assets/65799766/8a8d6e5a-4df6-4f88-ba0a-b1a3c0788b8b)

**Comment by K-vanc** [comment]
It looks like a parsing error on title element. I will share updated siteconfig when I am back

**Comment by K-vanc** [comment]
hi @stuckinthe 

I am (almost) back. Shared the fixed version of online.tivo siteconfig. Please check and let me know. It should fix that issue now
