### ISSUE TITLE
SiteConfig Request

### ISSUE THREAD

**Issue by dbmtech** [K-vanc/Tempest-EPG-Generator#33]
Hey K-Vanc

Is it possible to add Plex, Distro and Samsung TV Plus Siteconfig? Plex and Samsung TV xml file are present in [ENC]i.mjh.nz_0.siteconfig.php but these are not from source.

https://watch.plex.tv/live-tv
https://watch.plex.tv/live-tv/channel/shemaroo-bollywood

https://www.distro.tv/
https://www.distro.tv/live/free-classic-movies/

https://www.samsung.com/in/tvs/smart-tv/samsung-tv-plus/all-channels/

**Comment by K-vanc** [comment]
Hi,


On plex and samsung urls, there is no epg, just channels for information. I dont think these are source urls..


For distro, maybe can be done. Need to check it from pc

**Comment by dbmtech** [comment]
https://app.plex.tv/desktop/#!/live-tv/myPlex/tv.plex.provider.epg?pivotID=dvr.guide

for plex its showing tv guide in pc from above link.

**Comment by K-vanc** [comment]
i think it is(Plex) geo-blocked. it gives me no live tv source error from that link. I will try with my vpn later on

**Comment by K-vanc** [comment]
Distro.tv added into Multi Nation Folder

**Comment by dbmtech** [comment]
thanks! Distro working perfectly!

**Comment by K-vanc** [comment]
app.plex added into Multi Nation Folder

I think I am done with this topic since there is no source url for samsung tv

**Comment by dbmtech** [comment]
Thanks
