### ISSUE TITLE
SiteConfig Request [Indonesia]

### ISSUE THREAD

**Issue by devhik** [K-vanc/Tempest-EPG-Generator#34]
`HOME`
https://www.cubmu.com/live-tv

**Comment by K-vanc** [comment]
Hi to you also :)

I think can be done but I am away from pc now so tomorrow

**Comment by devhik** [comment]
> 

Ok. I'm happy to hear this news.. thanks bro

**Comment by K-vanc** [comment]
Welcome. I will update you when it is done. 

Note:

I trimmed sensitive information from your post due to some old fat italian spy around :)

**Comment by K-vanc** [comment]
hi @devhik

It has been added into Indonesia folder

**Comment by devhik** [comment]
> hi @devhik
> 
> It has been added into Indonesia folder

Ok saya akan mencobanya terimakasih bro

**Comment by devhik** [comment]
I also want to ask siteconfig thailand `tvsmagazine.com` so that I can retrieve all schedules, not just 4 schedules, do I need additional settings?
need to press show all day so that the 24 hour schedule is displayed..
![Screenshot_2023-08-20-14-05-55-432_com android chrome-edit](https://github.com/K-vanc/Tempest-EPG-Generator/assets/119641432/1f9bf691-b5e7-446e-8bdd-d40d92dcd84d)

**Comment by K-vanc** [comment]
I dont understand you question. tvmagazine.com  already exist in repo with 2 different language setting. You want to make your own version? If yes, you need to consider that epg urls and html displays are different thing. For grabbing, you need to focus epg urls. When you request that page, server is sending you data of all day but with some javascript work, only a few hours of data is being displayed.
