### ISSUE TITLE
Rotana

### ISSUE THREAD

**Issue by islamsabry2008** [K-vanc/Tempest-EPG-Generator#36]
In Siteconfigs/KSA/
Rotana is not working

**Comment by K-vanc** [comment]
Hi to you also..

It may be outdated since the time that has been shared in repo. I will try to check soon and update if website is still actively providing epg

**Comment by K-vanc** [comment]
New rotana siteconfigs have been added into KSA folder as Arabic and English languages.

Please check then I will close the issue

**Comment by islamsabry2008** [comment]
Works fine thank you so much
Now OSN.com in Multi Nation does not work

**Comment by K-vanc** [comment]
Welcome.

Osn have been already updated yesterday. Just use the latest version. You can use Siteconfig Updater option from main menu to get the most recent files

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/4308e111-bc10-462e-8769-23eaa7438518)

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/f8208c6c-658e-4739-acbd-16fc5e1e7c09)

**Comment by islamsabry2008** [comment]
![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/1075689/ec8b4e4d-f94e-479c-bcbc-fb28a0997610)

It gives this

**Comment by K-vanc** [comment]
It is your network, i guess. That max redirect means website is continuesly forwarding you another page instead of giving you requested page. It is another way of blocked unwanted ip adresses.

If you try with a vpn, better with a country close or same to the origin of website, you will get epg data.

**Comment by islamsabry2008** [comment]
I think it is my windows cause I tried on ubuntu and it works great
Thank you my friend

**Comment by K-vanc** [comment]
you are welcome. I am running it on windows without any issue. It could be also related with your different DNS settings etc. or somehow server may dislike your windows pc. There are many ways of identifying connecting devices and blocking in these days..

**Comment by islamsabry2008** [comment]
Take a look on this too
https://sat.tv/

**Comment by K-vanc** [comment]
Hi

I know that website but it is not worth to do. There are tons of channels which %95 of them has no epg and remaning %5 already available in other siteconfigs. It is at the very bottom of my to-do list for long time but I have no plan to waste my time with it currently

**Comment by K-vanc** [comment]
> Take a look on this too https://sat.tv/

Hi, added into Multi Nation folder

**Comment by islamsabry2008** [comment]
Great work as usual 
but Nilesat section is missing can you add i?
and Jawwy is stopped

**Comment by K-vanc** [comment]
I will check jawwy, tomorrow

**Comment by K-vanc** [comment]
Jawwy runs fine here, also there is no change on site or structure.

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/03a5206f-baa7-4a24-bda2-ad6697617ad0)

**Comment by K-vanc** [comment]
probably you are running out-of-memory. I tested above on 3 days request and 400MB memory was enough but when I repeat the request for 10 days, php run out-of-memory again so had to increase 500MB to make it work. This is the bad part of jawwy. It is giving around 120MB(changes) of data in 1 request includes all days for all channels and unfortunately there is no way to filter request..  Parsing such big data is very expensive operation in terms of php

**Comment by islamsabry2008** [comment]
so there is no hope?
