### ISSUE TITLE
Adding channels to xumo

### ISSUE THREAD

**Issue by stuckinthe** [K-vanc/Tempest-EPG-Generator#37]
Xumo has added new channels and I was trying to get the guide for these channels by opening up the play xumo channel xml file and adding the site_id as it was easy to figure out. I wasn't sure on the xmltv_id so this could be my issue. Tempest was unable to download the program data. 

The channel I was trying to add was boxing tv but there are others I'd like to add. Is this something I can do or is there more to it like editing the corresponding php file that would have to be done by you. Also, what is the difference between the play xumo 1 and 2 xml files?

**Comment by K-vanc** [comment]
Hi;

You cannot add/edit manually channels and expect them to work unless you are extreamly lucky. Why you are not using Channel Generator as it should be and explained here;

https://github.com/K-vanc/Tempest-EPG-Generator/blob/main/Siteconfigs/USA/0_Info%20for%20tvtv.us%20-%20tvpassport%20-%20tvguide%20-%20ontvtonight%20-%20%20directv%20-%20online-tivo%20-%20whattowatch%20-%20tvlistings.zap2it%20-%20play.xumo.com%20-%20channelmaster.md

You need to enter zip code of location you want and the missing channels you mentioned will be added if they really exist and/or have available epg.

Keep index version will run faster with multiple xumo channels but shall be grouped with only same location/zip code channels.

Example for zip code 10001 and 10002 channels, you channel selection shall be similar to;

10001|channel a
10001|channel b
.
.
10001|channel n
A non-xumo siteconfig channel
10002|channel a
.
.
10002|channel n

Non-keep index version will run abit slower compared to above version but can be grouped mixed with multiple location/zip code channels 

Example for zip code 10001 and 10002 channels, you channel selection may be in any combination;

10001|channel a
A non-xumo siteconfig channel
10001|channel b
10002|channel a
10001|channel n
10002|channel b

**Comment by stuckinthe** [comment]
Unfortunately, I cannot get this to work under Arch Linux. I am getting a missing module of iconvs. There isn't a package. I tried to install via pip and it gave me a warning about breaking the system  and you should install in a virtualenv and if you want to really install it said to use the flag --break-system-packages. I tried it with this flag anyways and still gave me the missing module error.

**Comment by K-vanc** [comment]
No, you shouldn't do that. You are trying to install iconv into your system which is not needed and also Tempest will not find/use it. Required iconv is a module of php's itself. It should be already installed but probably disabled.

Find your php.ini file and search for "iconv", you will see a line such as 

;ext=iconv

Then remove the starting semicolon and restart your php server. It will be enabled

**Comment by stuckinthe** [comment]
Thanks that fixed it. Thanks! You have to use key 10000 in order for it to pickup all the channels in xumo as it went from 164 (using key 10001) to over 300.
