### ISSUE TITLE
using ||#logo# issue

### ISSUE THREAD

**Issue by Toei79** [K-vanc/Tempest-EPG-Generator#40]
hi , i tried logo on site id for one channel.

but i get same logo in other channels that i dont modified, all from same group  like comes from directv.co for example.  
i get 10 channels from there, but i only modified logo in one, and i get this logo in at least 3 of 10 channels.

idk if its issue in my player or its from tempest , i clear cache on my case tivimate, because it not was displaying  epg what its fine right now.

also those channels are the next 2 channels  on list from channel indexer./ tempest configurator.

**Comment by K-vanc** [comment]
Hi;

i cannot know what your player is doing but you can easily understand by opening generated xml file and check channel which you set ||#logo# to see if icon tag is matching with what you set;
Example;

```
<channel id="RÚV">
    <display-name lang="is">RÚV</display-name>
    <icon src="https://www.sjonvarp.is/images/logos/RUV.jpg"/>
  </channel>
```

then you can check one of the channels that you mentioned as same logo appeared without your adjustment. if there is no icon tag or it is different, then it is related with your player. 

Anyway my short answer is; yes ,it is related with your player.

**Comment by Toei79** [comment]
for some reason its making for all

**Comment by K-vanc** [comment]
Hi,

So why you closed the issue? You found the solution? Can you copy/paste here your entire site_id line For the channel you put logo command?

I am Also using that command on my daily grab without any issue.

Also can you delete generated xml and rerun after setting permissions? Then check xmltv file again for icons. I remember as you have a neverending linux permission problem

**Comment by Toei79** [comment]
sorry i closed by mistake. 
other thread i closed because i run tempest and it shows getting epg.

9133008184|##|9200020413||#logo#http://192.168.2.131/Logos/Rcntv.png 
site id have this or just logo part.


no permissions are fine. i fixed that. its first that i check.

**Comment by K-vanc** [comment]
Thanks for the line. I will study on it tomorrow. I did tones of test on that logo command before publishing but I may be overlooked something. Could you please delete xml file and rerun? Also i need a few more information;

* are you getting epg for that channel with logo command?
* are you getting epg for the following channels after logo command?
* are you having similar issue with any other siteconfig?
* Could you please confirm your Tempest version(top right of screen)
* your operating system
* your php version
* your php server name

Thanks in advance.

**Comment by Toei79** [comment]
are you getting epg for that channel with logo command?
    yes :)
    
    are you getting epg for the following channels after logo command?
    hi yes those get epg.
    
    are you having similar issue with any other siteconfig?
    on tempest next one get same issue. 
![SHOT1057](https://github.com/K-vanc/Tempest-EPG-Generator/assets/79808610/675c5a8d-5ece-4134-a8a0-b7832b4dabb0)

    i attach a pic.
    
    Could you please confirm your Tempest version(top right of screen)
    rv1.5.1
    
    your operating system
    buntu 22.04.2 LTS 
    
    your php version
    PHP 8.1.18
    
    your php server name
    where its this one?

**Comment by Toei79** [comment]
all permissions good. i added a crontab to it so avoid if in the future, but still getting same

this time i added another logo so its two channels with logo 

![SHOT1058](https://github.com/K-vanc/Tempest-EPG-Generator/assets/79808610/8f275ceb-b752-4b12-a63f-42d2b400178a)

**Comment by K-vanc** [comment]
Ok, I confirm it is a bug. I missed to clear 1 variable from system memory before starting next channel so it follows the next channel if there is no channel logo element in following channel's siteconfig. if there is channel logo element in next channels, it overwrites its value. that's why didnt notice it.

Anyway I fixed it and will be available in next release(probably soon). Thanks for pointing it out.

**Comment by K-vanc** [comment]
Hi @Toei79 

Please confirm if issue solved then I will close the issue

**Comment by Toei79** [comment]
yea its working perfectly! thanks
