### ISSUE TITLE
Timeout issues and can't use sitemaker debug

### ISSUE THREAD

**Issue by stuckinthe** [K-vanc/Tempest-EPG-Generator#41]
I am using tempest on arch. I checked that I have the required modules (php -m), per my previous ticket, and it lists that I have them all. I am having issues grabbing data from plex as it says nothing found. I go into Sitemaker debug to check but when I follow the wiki and click debug i am dropped back to the main menu and nothing happens. I have also tried to collect EPG but the list gets halfway (11 of 25) through and the browser doesn't showing any progression but I look in the quide.xml file and it continues to about 2/3 of the way down and then stops. This happens through the browser and the command line.  I increased my max_execution on the php.ini to 0 to disable but this didn't help.

**Comment by K-vanc** [comment]
Hi, 

I thought everything was explained very clear but nevermind.

First, you dont need to check modules, if something is missing you will see it on screen of Tempest as missing module warning.

For debugging issue, it is explained here;
https://github.com/K-vanc/Tempest-EPG-Generator/blob/main/Siteconfigs/1_Siteconfig_Legends/README.md

For why Plex did not work for you, may be for this reason;
![Screenshot_20230904-221751_GitHub.jpg](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/20c375a1-28a9-47c9-b39a-092bf64ed765)

And probably, why it is terminated after a while explained here(close to end of main page);
![Screenshot_20230904-221820_GitHub.jpg](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/715f4312-8d39-420a-b75a-ed99017067d1)

**Comment by stuckinthe** [comment]
Sorry, I missed the timeout setting in help. I have a US IP but I can't get plex epg guide data. Also, the sitemaker debug doesn't work so I can't test it out.

**Comment by Toei79** [comment]
you are in usa? just curious, i can run on mine if you want to see.

**Comment by stuckinthe** [comment]
Yeah, I am in the USA.

**Comment by stuckinthe** [comment]
[04-09-2023 20:12:09] PHP Version : 8.2.9
[04-09-2023 20:12:09] Server Info : Apache/2.4.57 (Unix) PHP/8.2.9
[04-09-2023 20:12:09] Initializing...
[04-09-2023 20:12:09] Checking required modules...
[04-09-2023 20:12:09] guide.xml generated...
[04-09-2023 20:12:09] Grabbing started for 2 days
[                   ]
[04-09-2023 20:12:09] (1/1) Site: [ENC]app.plex.tv_0
[04-09-2023 20:12:09] Channel id: 63e63d26abacad42ed3d1acd
[04-09-2023 20:12:09] Xmltv id: The Price is RIght
[      Warning      ]
[04-09-2023 20:12:09] No show grabbed in 0.27 seconds
[                   ]
[04-09-2023 20:12:09] Grabbing completed...
[04-09-2023 20:12:09] 0 show grabbed in 0.27 second
[     Completed     ]
[04-09-2023 20:12:09] Tempest Overall Memory Usage: 4326KB
[04-09-2023 20:12:09] Tempest Peak Memory Usage: 11070KB

**Comment by Toei79** [comment]
i move to my tempest folder if you want i run here? lmk what channels i do right away

**Comment by Toei79** [comment]
> Yeah, I am in the USA.

what i need place on user key?

**Comment by stuckinthe** [comment]
I tried my user key and it said no channel block and then wiped out the xml file.

I had same issue with xumo and then I tried 10000 and it found all channels.

**Comment by Toei79** [comment]
whats the user key?

i know for ota guides its zipcode but idk for this one. let it blank no get channels

**Comment by stuckinthe** [comment]
I tried my zip code as user key but it said no blocks found and then emptied the xml file.

**Comment by Toei79** [comment]
i see same thing. being online thing i dont think require zip code but also there its not file instructions so let it blank suppose to work im guessing.

**Comment by stuckinthe** [comment]
When I leave it blank, I get no guide data.

**Comment by K-vanc** [comment]
ok, guys. It was my bad that I prepared that siteconfig remotely(and also blindly because didnt have vpn) so made some mistake in the siteconfig. Now I uploaded fixed siteconfig.

And there is no userkey for plex. If it is needed, I am adding a description into to relevant country folder

**Comment by K-vanc** [comment]
Did you checked permissions? And Could you please try grabbing with 1 channel from repo channel list?

Actually, i didnt look into channel creation part since it looked good to me

**Comment by Toei79** [comment]
yea permissions are fine

![SHOT1061](https://github.com/K-vanc/Tempest-EPG-Generator/assets/79808610/2d0874bb-905f-4746-a131-407f20c63c0f)
![SHOT1060](https://github.com/K-vanc/Tempest-EPG-Generator/assets/79808610/08d4e2b3-1274-478b-b608-911efe271146)

**Comment by K-vanc** [comment]
Ok, i tried to say, instead of channel creating, can you download channel list from repo and try to Generate epg?

**Comment by Toei79** [comment]
> Ok, i tried to say, instead of channel creating, can you download channel list from repo and try to Generate epg?

thats works.  looks like if you do generate channels delete all channels
instead go direct to to tempest and choose plex one and choose channels.  i able to see channel list now.

**Comment by K-vanc** [comment]
Ok, thanks for confirmation. As I said i didnt focus on channel creation part. Considered as it is fine. So will check channel creating part once again tomorrow..

**Comment by K-vanc** [comment]
@Toei79  and @stuckinthe 

hey, guys. I wonder if anyone else tried channel generation with updated siteconfig because it seems fine here despite "not working" comment of Toei79 without any change

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/a2e34124-2950-4dc1-93aa-e6a50e098491)

**Comment by K-vanc** [comment]
Just to be sure, i made some minor modification on channel creating part and re-uploaded new version but i didn't find any problem

**Comment by Toei79** [comment]
im gonna check it

**Comment by stuckinthe** [comment]
When I tried it, I got no channel blocks found and it emptied out the xml file.

**Comment by Toei79** [comment]
i just replace with ones you have right now , and still get issue, i read one apple one was changed like half hour ago.

**Comment by K-vanc** [comment]
No, it is static url adress. Any of you have chance to try with a vpn on? Too many unsuccessful attemps from yesterday may temporarily block your access to that page

**Comment by K-vanc** [comment]
Nevermind, I uploaded final version. Now it should be fine for all of you. I was using a special method to connect website without using vpn and strangely the page is responding me in xml data structure but to you(all regular users) in json structure so I prepared siteconfig according to xml structure. That's why i was able to channel create but you were not..

**Comment by Toei79** [comment]
now its working. with the new files.

**Comment by K-vanc** [comment]
good. I think we resolved everything in this subject

**Comment by K-vanc** [comment]
Hi @stuckinthe 

Is there any remaining problem or i will close the issue ?

**Comment by stuckinthe** [comment]
I am no longer having an issue with plex epg grabs. I can't figure out why I can't get Siteconfig debug to work as it drops me back to the start page when I click debug.

**Comment by K-vanc** [comment]
Hi @stuckinthe 

I have already sent you the link for siteconfig types but short answer is you cannot debug because I am not allowing you to debug any encrypted siteconfig

https://github.com/K-vanc/Tempest-EPG-Generator/blob/main/Siteconfigs/1_Siteconfig_Legends/README.md

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/5b4aec0c-4db0-4c80-9156-c949fb631580)

**Comment by Toei79** [comment]
idk but apple plex its same issue like this one here , or i do something wrong? file sizes dont change but i dont get any channels,  trying generating them or  in tempest configurator 

then streamguides its in same situation , idk if streamguides requires user key i dont see it.

**Comment by K-vanc** [comment]
Hi @Toei79 

Both siteconfigs are working after maintenance update. Both plex and streamguides do not need USERKEY, otherwise it would be explained in information files.. You need fresh channel list for both to work. File sizes increased 2,5-3KB after maintenance update. If you are telling sizes are still same, even this is enough to understand your doing something wrong on copy/pasting correct files. plex also sensitive for ip adress and even rejecting some VPNs. Since you didnt provide any other info/log etc, this is all i can help

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/a6c94c55-6edc-4222-85a8-bddbf6b581bf)

**Comment by Toei79** [comment]
hi man sorry im sorry,  all its fine,  i just change the server locally and i was checking old one. :/
then just checked like half hour ago and yes. all running fine.  on the new one where i updated all to latest
