### ISSUE TITLE
[ENC][EX]nowplayer.now.com[en]_0 Siteconfig Issue in Hongkong folder

### ISSUE THREAD

**Issue by dbmtech** [K-vanc/Tempest-EPG-Generator#43]
Can You check siteconfig [ENC][EX]nowplayer.now.com[en]_0.siteconfig.php.
No Epg Grabbing, "Wrong signatue type" error showing
![nowplayer](https://github.com/K-vanc/Tempest-EPG-Generator/assets/91105635/61f04386-8c16-4955-9c78-067bbbd0dc0a)

**Comment by K-vanc** [comment]
Hi;

Website is active and siteconfig is working.

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/4084a2e0-bb66-42c6-8495-971afdea911b)

You are receiving SSL error which related with your php's curl and openssl libraries. Possible solutions;

* you can downgrade your php's curl and openssl libraries to some level which these bugs ignored
* you can upgrade your php's curl and openssl libraries to latest 
* you can wait for website to fix problem on their ssl certificates
* If you are in Linux OS, you may try solution on below issue link;
https://github.com/K-vanc/Tempest-EPG-Generator/issues/31#issuecomment-1650973162
