### ISSUE TITLE
etisalat in UAE

### ISSUE THREAD

**Issue by islamsabry2008** [K-vanc/Tempest-EPG-Generator#48]
it is not working and give this
![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/1075689/3bf4ab24-1151-40d5-9d36-1b66042c9cf3)
Thanks in advance

**Comment by K-vanc** [comment]
it looks like website is not exist anymore. I will have a look if there is an alternative or new place for their epg but it could be the end of road

**Comment by K-vanc** [comment]
Damn, today I am unstoppable.. :)

Arabic and English versions are updated in UAE folder

**Comment by K-vanc** [comment]
Omg, do you believe some bastard is selling that siteconfig for 20 euros/year to poor people..

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/86feba41-8ab1-4320-b144-791b2792dba3)

I dont know if the world is so bad or I am so good(stupid)..

**Comment by islamsabry2008** [comment]
No just they are so greedy

**Comment by K-vanc** [comment]
You are welcome. Not all of them is too greedy but let's say (all-1). Just check my declaration file If you havent yet so you will understand better :)

https://github.com/K-vanc/Tempest-EPG-Generator/blob/main/DECLARATION.md
