### ISSUE TITLE
REQ: update Bosnia config tvarenasport.ba

### ISSUE THREAD

**Issue by febiferdiansyah** [K-vanc/Tempest-EPG-Generator#49]
Hi guys, could you please update the Bosnian config "tvarenasport.ba". I get the message "Request Error(url1): Operation timed out" if you have time please update it. Thanks

**Comment by K-vanc** [comment]
Hi. It seems something changed on website. I will have a detailed look tomorrow.

**Comment by K-vanc** [comment]
Hi, it is fixed and uploaded into Bosnia folder

**Comment by febiferdiansyah** [comment]
> Hi, it is fixed and uploaded into Bosnia folder

Well I will try, there is something I want to ask if tempest can be multiple threads connection, I tried to grab 350 channels and it took quite a long time up to 3-4 hours to complete it.

**Comment by K-vanc** [comment]
Tempest is a php file so you can run multiple threads at the same time as all php files. Only thing you have to keep in mind that php can perform only 1 listening in 1 port. This means if you try to run multiple tempest on same listening port(ex 8080), the second will start with the finish of first. But if you set another port for another php intense(ex 8090), you can run tempest on either ports at the same time. Also I know some users running it async with multiple virtual machine setups but I have never tried.  Anyway, this is not part of Tempest. You may google how to setup multiple php ports

**Comment by K-vanc** [comment]
> > Hi, it is fixed and uploaded into Bosnia folder
> 
> Well I will try, there is something I want to ask if tempest can be multiple threads connection, I tried to grab 350 channels and it took quite a long time up to 3-4 hours to complete it.

Hi, as of rv2.0.0.0, new synchrotron module added which allows parallel grabbing of same or different siteconfigs(or both) in selected configuration file based on user settings. This module will elevate Tempest into manager mode to start/coordinate/control & terminate multiple background tempest instances. Default setting is max. 5 instances each assigned to one different channel block(means all listed channels under same siteconfig) but you can change it from Configurator based on your hardware capabilities as limit is the sky.
