### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by TheDeatCrusher** [K-vanc/Tempest-EPG-Generator#5]
How can i change the logos for the channels?

**Comment by K-vanc** [comment]
Hi;

You can change the logos from "Channel Logo Pattern :" (including Detail Page 1/2)  for all unlocked or your own siteconfigs. Please note that entered input shall be a valid regex pattern based on page source. If you want to add a static url, "||#add#" command will stop regex engine and use followed string as channel logo. Any defined Tempest variables described in TempestWIKI.pdf such as "##channel##", "##xmltv_id##" and specificly designed "##cclogo##" which will transfer data from channel creation progress, may be used in logo url. For more details, please refer to TempestWIKI.pdf
