### ISSUE TITLE
tv24.co.uk TZ

### ISSUE THREAD

**Issue by indraprawiratamaharlis** [K-vanc/Tempest-EPG-Generator#52]
hi, I tried grabbing tv guide from the UK folder tv24.co.uk but the time is not right on my player ott navigator.. need to change the TZ to `-2h 00m` to get it right.. is there a way to not need that setting

**Comment by K-vanc** [comment]
hi. yes there is another way that as you did, you may notify me :) For confirmation, can I ask what is your timezone and local time now?

**Comment by indraprawiratamaharlis** [comment]
> hi. yes there is another way that as you did, you may notify me :) For confirmation, can I ask what is your timezone and local time now?

I run tempest on server github action with TZ:UTC time, on the OTT navigator player with TZ:WIB GMT+7 I don't understand about timezones in UTC
![Screenshot_2023-09-19-17-35-56-336_com android chrome-edit](https://github.com/K-vanc/Tempest-EPG-Generator/assets/119649186/632638da-26cf-43c6-941a-a5938e8e1a66)

**Comment by K-vanc** [comment]
can you try grabbing with this one again and check the result? This should fix it but I want to test before upload into repo. I thought that website is using London as timezone but seems it is adjusting showtimes based on local time of visitor
[[ENC][EX]tv24.co.uk_0.siteconfig.txt](https://github.com/K-vanc/Tempest-EPG-Generator/files/12659007/ENC.EX.tv24.co.uk_0.siteconfig.txt)

just replace .txt extension into .php after downloading

**Comment by indraprawiratamaharlis** [comment]
> can you try grabbing with this one again and check the result? This should fix it but I want to test before upload into repo. I thought that website is using London as timezone but seems it is adjusting showtimes based on local time of visitor [[ENC][EX]tv24.co.uk_0.siteconfig.txt](https://github.com/K-vanc/Tempest-EPG-Generator/files/12659007/ENC.EX.tv24.co.uk_0.siteconfig.txt)
> 
> just replace .txt extension into .php after downloading

OK I will try it..

**Comment by indraprawiratamaharlis** [comment]
The resulting grabber still doesn't match what is displayed on the web.. I also tried on Tivimate with the EPG that was generated with the PHP config above but it still doesn't match..
I tried to upload an image but couldn't

**Comment by indraprawiratamaharlis** [comment]
Screenshot
Ott
https://ibb.co/KGP7Qn0

Web
https://ibb.co/sK2612n

**Comment by indraprawiratamaharlis** [comment]
> can you please upload also generated xml file? BTW did you clear all epg and reload for OTT?

There's something wrong with my github account, so I can't upload anything.
  I have custom `xmltv_id` specifically to make it easy to remember 😅
 xml file generated https://file.io/N1vpC5qF6ny0

**Comment by indraprawiratamaharlis** [comment]
Yes, I also deleted the APK data, even tried it on tivimate too...

**Comment by K-vanc** [comment]
It is really strange. I thought website is adjusting showtimes but they are giving shows in a very different timezone for UK.. Please check this one, now it should match because all aligned for me now and when compared with your file..

[[ENC][EX]tv24.co.uk_0.siteconfig.txt](https://github.com/K-vanc/Tempest-EPG-Generator/files/12660432/ENC.EX.tv24.co.uk_0.siteconfig.txt)

**Comment by indraprawiratamaharlis** [comment]
> It is really strange. I thought website is adjusting showtimes but they are giving shows in a very different timezone for UK.. Please check this one, now it should match because all aligned for me now and when compared with your file..
> 
> [[ENC][EX]tv24.co.uk_0.siteconfig.txt](https://github.com/K-vanc/Tempest-EPG-Generator/files/12660432/ENC.EX.tv24.co.uk_0.siteconfig.txt)

It's been resolved, the grabbed results match those displayed on the website, thank you, bro

**Comment by K-vanc** [comment]
welcome, I will update repo with same

**Comment by indraprawiratamaharlis** [comment]
> welcome, I will update repo with same

**Comment by indraprawiratamaharlis** [comment]
> > welcome, I will update repo with same

hi, it seems that for "spain" `movistarplus` also has the same problem, maybe you should check it too.. if you have free time.. 🙏

**Comment by K-vanc** [comment]
Yeah, they revised their timezone also. I have uploaded revised into Spain folder.

Btw this subject was for tv24.co.uk and it was resolved. For different subjects, please open new issue or ask without reopening an unrelated subject. It causes difficulties for people searching issues
