### ISSUE TITLE
update config firstmedia

### ISSUE THREAD

**Issue by febiferdiansyah** [K-vanc/Tempest-EPG-Generator#53]
Hi, indonesia folder "firstmedia" No show grabbed, maybe there is a change in the web grabbed.. can you fix it. Thanks

**Comment by K-vanc** [comment]
hi, probably cannot help, at least at the moment. It seems currently their website is down.. Are you able to visit below site?

https://www.firstmedia.com/

**Comment by febiferdiansyah** [comment]
> hi, probably cannot help, at least at the moment. It seems currently their website is down.. Are you able to visit below site?
> 
> https://www.firstmedia.com/

Geo-blocked 😅

**Comment by K-vanc** [comment]
i love self-resolved topics :smiley:

**Comment by febiferdiansyah** [comment]
> i love self-resolved topics 😃

Is it possible to retrieve epg data in json format.. this link [json](http://202.77.116.75/metadata/delivery/GLOBAL/btv/programmes?filter={"locale":"en_GB","serviceRef":{"$in":["LYS000000033"]},"period.start":{"$lt":1695920400},"period.end":{"$gt":1695834000}}&sort=[["period.start",1]]&fields=["id","isCatchUp","period","serviceRef","Synopsis","Title"]&offset=0&limit=9999)  I took from the firstmediax app.. and can be accessed with any ip

**Comment by K-vanc** [comment]
As long as you see the epg, there is always a hope.. I will have a close look but couldnt see the channels

**Comment by K-vanc** [comment]
this could help. Let me check what we can do

**Comment by K-vanc** [comment]
can you see any url for logos?

**Comment by febiferdiansyah** [comment]
> can you see any url for logos?

[here](http://202.73.98.253/pics/FMX/EPG/)

**Comment by K-vanc** [comment]
thanks already found by mistake

**Comment by K-vanc** [comment]
added into Indonesia folder. Thanks for your contribution

**Comment by febiferdiansyah** [comment]
> added into Indonesia folder. Thanks for your contribution

Wow.. You're welcome, I'll give it a try

**Comment by K-vanc** [comment]
noticed a small problem in logos and reuploaded
