### ISSUE TITLE
Swedish channels Tv4 sport 1 to 5 issue with scraping epg

### ISSUE THREAD

**Issue by Jimpan81** [K-vanc/Tempest-EPG-Generator#56]
Hello ! 
Im scraping epg from Swedish Tv.nu site and all channels scrapes fine . All info and pictures. Thanks !  But the issue is the Tv4 sport channels , 1 to 5 ( 5 channels)
It has no picture and no info of what game is on . Tv.nu has the info but Tvheadend and Kodi has not . See Screenshots 
![IMG_0487](https://github.com/K-vanc/Tempest-EPG-Generator/assets/106754456/d25bf9b5-079c-4da5-bcfe-0428c8d862df)
![IMG_0486](https://github.com/K-vanc/Tempest-EPG-Generator/assets/106754456/87062efa-7738-496b-90b3-460e38f4236a)
![IMG_0485](https://github.com/K-vanc/Tempest-EPG-Generator/assets/106754456/67db6fed-c6d6-47a8-80f5-aa579ae9ea2c)

**Comment by Jimpan81** [comment]
Edit looks like its the same on all sport events 
One more example from V sport fotball 
![IMG_0488](https://github.com/K-vanc/Tempest-EPG-Generator/assets/106754456/fbf0a88f-3993-4163-bb66-7642936f3e8b)

![IMG_0489](https://github.com/K-vanc/Tempest-EPG-Generator/assets/106754456/a77bba5d-cfd9-43db-8eeb-ad346618ea1e)

**Comment by Toei79** [comment]
maybe you can try the logo feature? you can add to those channels. idk whats going on there if its epg or something on tvheadend, tvheadend its kinda friendly with epg formats.

**Comment by Jimpan81** [comment]
Logo is not the issue . Its the program picture/ fanart thats missing and info of whats game is on . Must be av scaper issue because all other non sport channels has all ? Logo , info and picture

**Comment by Toei79** [comment]
imo you need check if its available  on the webpage so it be scrapper issue. maybe

**Comment by K-vanc** [comment]
Yes, it is a new siteconfig issue. The missing elements you mentioned are located in detail pages but website seemed to make some changes on detail pages requests of some channels so for those channels, you are not currently accessing detail pages and thats why you are not receiving that elements.

I AM 'IN VACATION as I wrote to main page so you can use other Sweden siteconfigs till I return and fix it

**Comment by Jimpan81** [comment]
Thanks for looking, no hurry enjoy your vacation 😊

**Comment by K-vanc** [comment]
Hi @Jimpan81 . I am back (unfortunately).. You can get updated tv.nu siteconfig which resolves different url problem from Sweden folder.

**Comment by Jimpan81** [comment]
Thanks!

**Comment by Jimpan81** [comment]
@K-vanc 
Icon and desc is ok but category seems to be missing on the sportschannels you fixed. 
Some events has ”live” but not all. Tv.nu has the info but not in Tempest xml 
![IMG_0685](https://github.com/K-vanc/Tempest-EPG-Generator/assets/106754456/f6a735aa-b2ea-4dd0-8b82-d46cff5ae3ba)
![IMG_0688](https://github.com/K-vanc/Tempest-EPG-Generator/assets/106754456/852b38fa-1ca3-4d7f-bda8-0a602ed2ccd3)
![IMG_0687](https://github.com/K-vanc/Tempest-EPG-Generator/assets/106754456/651457f7-2be3-42a6-b314-daedc82eada1)

If you have time 😊🙏

**Comment by K-vanc** [comment]
I dont understand what part you want to see as catagory? It is grabbing all categories which are labeled as genre, category or movie/series

**Comment by K-vanc** [comment]
Anyway.. i Will have a look again tomorrow if something else can be added...

**Comment by Jimpan81** [comment]
Category should be ”Ishockey” in this specific case from picture above . But could be any other sport aswell on other events

**Comment by Jimpan81** [comment]
Ishockey =Icehockey  ( a Word in swedish). 
Fotboll = Fotball  
Some more examples of different sports
![IMG_0691](https://github.com/K-vanc/Tempest-EPG-Generator/assets/106754456/dbdec688-5f15-426a-af57-66c05cf7f8d9)
![IMG_0689](https://github.com/K-vanc/Tempest-EPG-Generator/assets/106754456/f75f6429-52fd-415d-a691-6cc2e824117d)

**Comment by K-vanc** [comment]
updated

**Comment by Jimpan81** [comment]
Thanks ! Looking good . Amazing 🙏🤩

**Comment by K-vanc** [comment]
it is already being processed. If a show has "isRerun: true", you will get it as "previously-shown" tag which defined for using re-broadcasted shows. But for many sports channel, data is coming as "isRerun: false" so Tempest not capturing them.

**Comment by K-vanc** [comment]
normally, i am preparing siteconfigs according to xmltv.dtd. and not personalizing them by moving defined element to under some other tags. Personalization shall be done by inverter module or users have to learn making their own siteconfigs but today is christmas so I will make one exemption for you. Still will not add it into repo but this will store "Repris" value as category element similar to "live". (rename file extension into .php) 

[[ENC]tv.nu_0.siteconfig.txt](https://github.com/K-vanc/Tempest-EPG-Generator/files/13766241/ENC.tv.nu_0.siteconfig.txt)

**Comment by Jimpan81** [comment]
Thanks and i get it ! 
Maybe you could add the rerun date and insert it in descriptions ? 
Från = from in swedish 
![IMG_1060](https://github.com/K-vanc/Tempest-EPG-Generator/assets/106754456/f8936ee1-c06b-4e0d-8c11-b96bd4ed9b4f)

**Comment by K-vanc** [comment]
ok, I added final revision into Sweden folder. Now it grabs repris as category tag and captures first show date into previously-shown element as below;
>
    <programme start="20231226060000 +0000" stop="20231226081500 +0000" channel="TV4 Fotboll">
    <title lang="sv">Villarreal CF - Celta de Vigo</title>
    <desc lang="sv">Från Ceramic Stadium i Villarreal, Valencia, Spanien.</desc>
    <category lang="sv">Sport</category>
    <category lang="sv">Repris</category>
    <category lang="sv">Fotboll</category>
    <category lang="sv">Laliga</category>
    <icon src="https://new.static.tv.nu/243817257?forceFit=0&amp;height=720&amp;quality=80&amp;width=1280"/>
    <previously-shown start="20231220000000"/>
    </programme>

This date pattern is the standard definition for previously shown element as "YmdHis" format. If you want, you can move it into description or some other element by using inverter module and even change the date display with some replace commands there. 

>
    <programme start="20231226060000 +0000" stop="20231226081500 +0000" channel="TV4 Fotboll">
    <title lang="sv">Villarreal CF - Celta de Vigo</title>
    <desc lang="sv">Från Ceramic Stadium i Villarreal, Valencia, Spanien.
    Genre: Sport,Repris,Fotboll,Laliga
    First Shown: 20231220</desc>
    <icon src="https://new.static.tv.nu/243817257?forceFit=0&amp;height=720&amp;quality=80&amp;width=1280"/> 
    </programme>

I will not make any other change on tv.nu siteconfig unless they make some change in website

**Comment by Jimpan81** [comment]
You are the best 🤩👌

**Comment by K-vanc** [comment]
> @K-vanc
I try to understand the inverter from wiki but i dont exact understand , so hoping you could give me the line for deleting "play" "movie" and "series" from category for tv.nu ? Cause i have them in swedish language also: "film" and "serie" so there is no need to have them again i english. Thanks again for all your work!

Hi @Jimpan81 ,

I moved your question to this issue since i am keeping main issue only for announcements etc. and trying to keep it clean from user problems

Inverter is the most powerful module of Tempest after grabbing engine and you can do it more or less whatever you want instantly and without extra memory usage. It works with first in/first out logic so below code should do what you need;

["category":||#replace#((?:,)?(?:play|movie|series)(?:,)?)||]["desc":"##desc##","#\nGenre: #category(,)##"]["category":||#delete#]

In this code, there are 3 command blocks wrapped inside "[ ]". First Block is for replacing play/movie/series words with nothing(so they will be deleted) in category element. (It is case-sensitive and i wrote it based on your message. Not tested so if something is different, modify accordingly)

Second block for description element. It will keep description's original value(##desc##) and add to end of it modified category element with a "new line"(\n) + "Genre: " Word. I used (,) for seperator so if there are multiple category values, they will be seperated with ",".

Last Block is deleting category element from xmltv structure since they have been added into description.

**Comment by Jimpan81** [comment]
Thanx !
["category":||#replace#((?:,)?(?:Play|Movie|Series)(?:,)?)||] worked fine. 
In the future , when you do some other work on tv.nu maybe you could remove the 3 above? As them are not needed for swedes. But all good for now
