### ISSUE TITLE
no issue, advice?

### ISSUE THREAD

**Issue by Toei79** [K-vanc/Tempest-EPG-Generator#57]
on my epg i have like 100 channels,  mixed from online and ota channels,

many online channels are only 3 days vs 7 days on ota ones,  so whats best way, do every 3 days or create 2 separate files and joining after? it takes some time processing anyway i have cronjob at night.

**Comment by K-vanc** [comment]
Hi, you can use all channels in same configuration by setting your configuration's Timespan to 6 so Tempest will run to grab 7days if available And max days of other siteconfigs which has less than 7days epg as example 3 days.

Also enable fusion with level 0 so if any channel fails, Tempest will restore existing data and update new shows.

Then you can set to run this configuration daily or with 3days intervals via cron/scheduled tasks

**Comment by K-vanc** [comment]
Closed due to inactivity
