### ISSUE TITLE
Siteconfig Request

### ISSUE THREAD

**Issue by febiferdiansyah** [K-vanc/Tempest-EPG-Generator#58]
Hi, if you have free time... can you make a siteconfig for hosting this event? Thank You 
web: https://garuda.tv/jadwal-acara/

**Comment by K-vanc** [comment]
Sure but you need to wait 1 week  more(i am in last week of my vacation)

**Comment by K-vanc** [comment]
Hi @febiferdiansyah 

It is added into Indonesia folder
