### ISSUE TITLE
Wrong episode/ season from Tv.nu

### ISSUE THREAD

**Issue by Jimpan81** [K-vanc/Tempest-EPG-Generator#63]
tv.nu season / episode numbers is differente from grabbed data 

![IMG_0778](https://github.com/K-vanc/Tempest-EPG-Generator/assets/106754456/a98f1797-b72f-4863-a736-e1bf530a9dfa)
![IMG_0779](https://github.com/K-vanc/Tempest-EPG-Generator/assets/106754456/127c63f7-be48-46e1-94d1-abc758869d66)

**Comment by K-vanc** [comment]
I saw the issue and fixed but before start publishing siteconfigs, I am working on an update and has to complete it so you need to wait for 1-2 days more(I think I can finish)

**Comment by K-vanc** [comment]
updated version added into Sweden folder. It should be ok now
