### ISSUE TITLE
TV4 Hits no data grabbed 

### ISSUE THREAD

**Issue by Jimpan81** [K-vanc/Tempest-EPG-Generator#67]
Hi ! 
All channels from tv.nu works but not the channel TV4 hits. Grabbed and regrabbed but no data in xmltv ( tv.nu has the data)
![IMG_1045](https://github.com/K-vanc/Tempest-EPG-Generator/assets/106754456/6596f963-0503-4642-86c0-1a101070ccc8)
![IMG_1046](https://github.com/K-vanc/Tempest-EPG-Generator/assets/106754456/c4329f9b-108e-4a9c-8f96-25c277c290f8)

**Comment by K-vanc** [comment]
Hi, can you generate epg only for tv4 hits and attach the generated xml file? it works fine and I dont understand what you mean by no data? The photo you attached is showing grabbed epg data. It is filtering only first line of program tag but if you open with a normal editor, you will rest of data below those lines.. 
[123.txt](https://github.com/K-vanc/Tempest-EPG-Generator/files/13760777/123.txt)

**Comment by Jimpan81** [comment]
Sorry for the noice , working fine now all suddenly .  Dont know what happended but i has no guide for a couple of days for that channel . But all good now
