### ISSUE TITLE
Siteconfig request : https://gigatv.3bb.co.th/epg

### ISSUE THREAD

**Issue by oldpoem** [K-vanc/Tempest-EPG-Generator#7]
Please create siteconfig for https://gigatv.3bb.co.th/epg.  They have some exclusive channels that aren't available in other Thailand siteconfigs.

There is english version as well.  https://gigatv.3bb.co.th/en/epg . Seem like english only in menu interface  not EPG data.

This site epg is probably main reason I'm still using webgrab+. 

Best regards.

**Comment by K-vanc** [comment]
Hi. It is added to my to-do list. I will update status on Saturday.

**Comment by K-vanc** [comment]
It has been added to Thailand folder

**Comment by oldpoem** [comment]
Thank you.
