### ISSUE TITLE
FR: television.telerama.fr

### ISSUE THREAD

**Issue by devhik** [K-vanc/Tempest-EPG-Generator#71]
Stuck only at Checking required modules...
![Screenshot_2024-01-02-17-41-16-242_com android chrome-edit](https://github.com/K-vanc/Tempest-EPG-Generator/assets/119641432/d43cb80d-d7b1-49c2-adaa-23f6b786a911)

**Comment by K-vanc** [comment]
It is not stucking on checking modules.. it is grabbing and that siteconfig is slow so you have to wait or reduce max days...

**Comment by K-vanc** [comment]
![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/3bb84655-ce39-4934-9081-4df61c0348b2)

**Comment by devhik** [comment]
> It is not stucking on checking modules.. it is grabbing and that siteconfig is slow so you have to wait or reduce max days...

OK, thanks for the explanation

**Comment by K-vanc** [comment]
Instead of that one, you may try api.telerama. they are using same source but server response speed is better
