### ISSUE TITLE
Live Events

### ISSUE THREAD

**Issue by liben96** [K-vanc/Tempest-EPG-Generator#73]
Hi guys,

Is there a way to know if the event/program is live? Any flags or something in the xml object?

Thanks

**Comment by K-vanc** [comment]
Hi, there is no standard element defined for "live" events in xmltv.dtd.

As usual, if it is available or any kind of identifier exists in the source, i am adding it as category element into siteconfigs that i made by default. If there is nothing in source, there is no way to guess and add it into xml.
