### ISSUE TITLE
Hungary/musor.tv question

### ISSUE THREAD

**Issue by tamkov** [K-vanc/Tempest-EPG-Generator#74]
Hi K-vanc,
First of all, thank you very much for your work, I finally found the best epg grabber program for me.
I see that you are still working on the siteconfig files, but you are already over Hungary.
The Hungary/musor.tv only grab one day, always that day (today).
In the same config I use the Mediaklikk and tvmustra too, they are fine, the requested 5 days will come.
I tried to find the error in the musor.tv siteconfig file, but I couldn't figure out what's causing it :(

Can I check / adjust something?

BR,
Tamas

////////
I don't see any errors in the log:

[07-01-2024 00:34:13] Tempest Version : rv1.6.0.0-2310141014
[07-01-2024 00:34:13] System Info : Linux raspberrypi 6.1.21+ #1642 Mon Apr  3 17:19:14 BST 2023 armv6l
[07-01-2024 00:34:13] PHP Version : 7.4.33
[07-01-2024 00:34:13] Server Info : Command Line Interface (Cli)
...
[07-01-2024 05:50:14] (208/209) Site: musor.tv_0
[07-01-2024 05:50:14] Channel id: ERDELY_TV
[07-01-2024 05:50:14] Xmltv id: musortv-ErdelyTV.hu
[07-01-2024 05:50:34] 22 shows grabbed in 20.03 seconds
[                   ]
[07-01-2024 05:50:36] (209/209) Site: musor.tv_0
[07-01-2024 05:50:36] Channel id: PANNON_TV
[07-01-2024 05:50:36] Xmltv id: musortv-PannonTV.hu
[07-01-2024 05:50:59] 28 shows grabbed in 23.30 seconds
[                   ]
[07-01-2024 05:51:20] Grabbing completed...
[07-01-2024 05:51:20] 31055 shows grabbed in 5 hours 17 minutes 7.16 seconds (19027.16 seconds)
[     Completed     ]
[07-01-2024 05:51:20] Tempest Overall Memory Usage: 5346KB
[07-01-2024 05:51:20] Tempest Peak Memory Usage: 13776KB
[07-01-2024 05:51:31]
[07-01-2024 05:51:31] Guide.xml.gz file created

**Comment by K-vanc** [comment]
Hi, yes I thought i can finish siteconfig maintenance within a week but reached half of it within 2 weeks..

You are right, i missed that. Uploaded fixed version, please redownload new siteconfig.

**Comment by tamkov** [comment]
Thank you very much, that was fast. 
Have a nice day!

BR,
Tamas

**Comment by K-vanc** [comment]
you caught me on a very free moment which happens very rarely 😃

**Comment by tamkov** [comment]
Hi,
I have one more question, [ENC]rakuten.tv[hu] intentionally grab only one day (Today)?
//Siteconfig Maximum Days : 7.1
I can't fix it because you coded it.
(You updated it 4 days ago)

BR,
Tamas

**Comment by K-vanc** [comment]
Hi, there is nothing to be fixed in Rakuten. It supports upto 7 days but not all channel has that much data available as some channels have only 1 day data in their api. Tempest is grabbing whatever available upto your day request. 

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/2db187f5-cda6-44e1-b194-0f2b7a03a591)

**Comment by tamkov** [comment]
Hi,
Interesting that it works for you, I will try set it to 6 days.
I set it to 7 days, then it doesn't download anything.
If I change it to one, it's fine.
I'll send a screenshot tonight.

Have a nice day!

**Comment by K-vanc** [comment]
it could be related with api. If you request too often, some apis may block you temporarily or may return an empty string.

If you write down channel also, I may try to reproduce

**Comment by tamkov** [comment]
![rakuten 7days](https://github.com/K-vanc/Tempest-EPG-Generator/assets/19505842/71ff68c7-8f6e-4ec3-9c92-f37ab1b76797)

**Comment by tamkov** [comment]
![rakuten 6days](https://github.com/K-vanc/Tempest-EPG-Generator/assets/19505842/5ac77ce2-ac71-4b1c-83ca-919a13920995)
![rakuten 1days](https://github.com/K-vanc/Tempest-EPG-Generator/assets/19505842/fc83c132-85e1-49ac-a3fc-c804cf3875d6)

**Comment by K-vanc** [comment]
From your configuration file increase timeout setting. Yours set to 5 seconds so request for more days takes more time to load but when it reachs 5seconds, Tempest stops and making new request.

Set it 20 and it will work

**Comment by tamkov** [comment]
Ok, I'll set it to 20, thanks.

**Comment by K-vanc** [comment]
It is about server as sometimes it is responding faster but if you dont increase timeout value, it will fail again later.
