### ISSUE TITLE
[ENC][EX]tvprofil.com_0

### ISSUE THREAD

**Issue by devhik** [K-vanc/Tempest-EPG-Generator#75]
It's not working for me... maybe you can check.

EPG Generator: Request Error(url2): The requested URL returned error: 400
Channel Generator: No Channel Block Found

**Comment by K-vanc** [comment]
Hi, they changed everything, you can use new version

**Comment by devhik** [comment]
> Hi, they changed everything, you can use new version

Ok, thanks for the hard work
