### ISSUE TITLE
How do i automate epg generator to regenerate 

### ISSUE THREAD

**Issue by pinsharp** [K-vanc/Tempest-EPG-Generator#78]
## Issue Type

Please choose your issue type
* [ ] Question (i am new Newbie)

## OS Details (Not required for Request)

Please choose your OS
* [ ] Android

Please write your version details (Below not required for Docker)

* PHP Version: 8.2.6

* Tempest Version: Latest

* Web Server Name: KSWEB/localhost

## Current Behavior (Not required for Request)

everything works as expect but i need to automate so that it capture/update epg every 6 hours something like that 
i am running webserver on android using KSWEB app..  accessing php script via LOCALHOST

## Expected Behavior (Not required for Request)

how can i regenrate/update the epg automatically after certain time frame or dring boot or something like that

**Comment by K-vanc** [comment]
hi,

automatic generation in android is out of my scope as Tempest. There were some automatic tasking  applications on previous android versions such as Tasker etc. but i am not sure if you can achieve this by using only android.. 

As far as I know, android php servers dont have direct support for php-cli and also there is no direct implementation for curl or cron so probably you cannot trigger script execution without your interaction. I think only way could be via a linux terminal through Termux but it will be very complicated to do for a Newbie and there is no guarantee.

Anyway, maybe some other user can mention if there is an easier way

**Comment by pinsharp** [comment]
okay.
my actual paln is to run local host  so that i dont have realy on any external webservers which may go down of crashes..etc
can we automate in php webhosting services if yes means i can opt for free webhosting and process 
and generate private epg.xml.gz for my own personal use
does this idea works???

**Comment by K-vanc** [comment]
depends on webhosting service you use. If they have ssh access, then yes you can use it with php command line request. If not, you will need another pc to make an automated curl request to your webhost as trigger. 

For Google Cloud, I have no idea.

**Comment by pinsharp** [comment]
there is schduker in KSWEB app i dont know what to do would this help to auto task???
![Screenshot_20240109-122428_KSWEB](https://github.com/K-vanc/Tempest-EPG-Generator/assets/40915412/0db34df1-3588-402c-900a-865d8b274a55)

would this works??

**Comment by K-vanc** [comment]
yes, probably but i dont know their settings.

Click use root, on command line paste;

php tempest.php engine=Generate createxmlgz=on

and for the time setting at top, use below link for explanation;

https://cloud.google.com/scheduler/docs/configuring/cron-job-schedules

If not works, try with clicking php script option. As I said, this it not my application nor more is my scope of work..

**Comment by pinsharp** [comment]
It works like scheduler
It runs the script on cron time assigne
It needs a pathed shell script so that it execute on assigned time correctly 
Can you help provided command line as executable script or something I can map With path with??

**Comment by K-vanc** [comment]
I have already wrote on previous as what you need to do

Command line, paste below;

`php /path/of/your/tempest.php engine=Generate createxmlgz=on`

Click use root

Top Cron expression is for running interval. I already gave you reference link for stars.

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/67519349-58b1-46c0-a2c6-21b1510fa83f)

Test with those, what else I can do?

**Comment by pinsharp** [comment]
Scripts gets executed 

But ends with this log
`12px}}</style><title>Tempest</title></head><body><div id="versx">rv1.6.0.0-2310141014</div><center><h2>Tempest EPG Generator</h2></center><form action="" method="post" enctype="multipart/form-data" autocomplete="off"><center>Select mode <select name="tko"><option value="0">--select--</option><option value="1">Siteconfig Maker</option><option value="2">Siteconfig Debugger</option><option value="3">EPG Generator</option><option value="4">Channel Generator</option><option value="5">Siteconfig Editor</option><option value="6">Tempest Configurator</option><option value="7">Siteconfig Updater</option><option value="8">Tempest Updater</option></select><br><br><input type="submit" value="Proceed" name="submit"></center></form></body></html>`

Any idea mate???

**Comment by K-vanc** [comment]
It didnt used your parameters as command line and interpreted it as web site visit. Maybe KSWEB dont have php-cli

**Comment by pinsharp** [comment]
i think there is no option 
if you get any option kindly send it i will give a try 
thanks for your support mate

**Comment by K-vanc** [comment]
Maybe it works, maybe not. I looked on the Google but there is no explanation about how it is working. Hard to tell anything since i dont have app

**Comment by pinsharp** [comment]
yeah but i dont know coding so i cant modify anything apart from you gave 
if you have time in future kindly give a try it woulbe much easier for you to trobuleshoot
already this script is awesome if it works on android too...it will be even more awesome

**Comment by pinsharp** [comment]
Forget to mention this 
This was code it was created by app as executable php script

`$$PHP_CGI$$ -c /data/user/0/ru.kslabs.ksweb/components/php/conf/php.ini -f /storage/emulated/0/htdocs/tempest.php engine=Generate createxmlgz=on`

May be it might help

**Comment by pinsharp** [comment]
sucess i just changes CGI to CLI everything worked perfectly man coding one hell of a job......hehehe

**Comment by K-vanc** [comment]
lol good to hear. 

Yes, 
CGI => Graphical Interface
CLI => Command line Interface

So thats why it was interpreted as website visit on previous runs.

If you paste screenshot of your cron setup here from app interface, it can help others who are willing to use KSWEB cron

**Comment by pinsharp** [comment]
### **Android cron setup**
App used:KSWEB

code `$$PHP_CLI$$ /yourpath/tempest.php engine=Generate createxmlgz=on`

![Untitled-1](https://github.com/K-vanc/Tempest-EPG-Generator/assets/40915412/d6bfe110-2f97-4d5a-92c9-a009eca44e41)

Thanks to Kivance for support

**Comment by K-vanc** [comment]
Well thanks to you for sharing, I didn't do anything. Wow, looks cool. So it is using totally custom command syntax. It is really strange as they dont have any document about how to use. 

Anyway, I noticed 1 small issue on last screenshot for "open_basedir" restriction is on. Probably all encrypted siteconfigs will not work for you while this error is on. It is strange because KSWEB doesnt have this error on GUI mode. Did you try grab any [ENC] siteconfig? Maybe enabling "Use root" option on third pic may help since I dont see any other option here.

**Comment by pinsharp** [comment]
You are right it is not fetching [ENC] siteconfigs not just in automation script totally in this webserver... I don't know how to fix this...is there any settings or name i should check 
If I get some lead i can check it...

**Comment by K-vanc** [comment]
It is called as it is. open_basedir is a directive. If there is nothing in the settings something like this, maybe you can check inside php.ini manually. From your previous post, this is the location of php.ini file;

/data/user/0/ru.kslabs.ksweb/components/php/conf/php.ini

Search inside for open_basedir and disable it. Save the ini and restart server so it should work then

**Comment by pinsharp** [comment]
I have attached php.ini renamed as txt
I am unable to find that exact name 
So kindly have a look and guide me where to add that line
[php.txt](https://github.com/K-vanc/Tempest-EPG-Generator/files/13875479/php.txt)

**Comment by K-vanc** [comment]
If they are not using a random name, it is not there..

Anyway, i added it to top of attached file to try your luck. If it is not system wise hardcoded, after replacing ini and restarting server, it may work.. 

![php.txt](https://github.com/K-vanc/Tempest-EPG-Generator/files/13876111/php.txt)

**Comment by pinsharp** [comment]
Hey it's working!!!
At it's a pure sucess 
Actually you just added one line right???

Thank you so much

**Comment by K-vanc** [comment]
Yes, added force disable it. Enjoy

**Comment by pinsharp** [comment]
One last request kindly check dthhelp.net siteconfigs
Finally thank you so much ❤️

**Comment by K-vanc** [comment]
I am done for today

**Comment by pinsharp** [comment]
how to run cronjob at every reboot???

**Comment by K-vanc** [comment]
I don't know. For Tempest, I didn't code any cron setting so maybe better search how for your operating system?

**Comment by pinsharp** [comment]
thanks for your response
