### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by TheDeatCrusher** [K-vanc/Tempest-EPG-Generator#8]
I grabbed epg from the directv site config but parts of the epg has no information

**Comment by K-vanc** [comment]
Any example about what you grab for which channel or I need to guess them?

**Comment by K-vanc** [comment]
I randomly pick 1 channel and grabbed attached data. Maybe channel you pick, only have limited data. Tempest is a tool to grab existing data. It cannot create missing data 
![Screenshot_20221222-222509_HTML Viewer](https://user-images.githubusercontent.com/97025515/209211322-22fe299a-04b4-402a-be01-43171d824ed2.jpg)

**Comment by K-vanc** [comment]
i am closing the issue since no reply for 3 days
