### ISSUE TITLE
Taiwan Homeplus EPG Url Changed

### ISSUE THREAD

**Issue by Wangliann** [K-vanc/Tempest-EPG-Generator#85]
Hi，

The EPG address of the homeplus website in Taiwan has been changed, and the [original code](https://github.com/K-vanc/Tempest-EPG-Generator/blob/main/Siteconfigs/Taiwan/%5BENC%5Dhomeplus.net.tw_0.siteconfig.php) is no longer available. Please help update it when you have time. 

[https://www.homeplus.net.tw/cable/product-introduce/digital-tv/digital-program](https://www.homeplus.net.tw/cable/product-introduce/digital-tv/digital-program)

Thanks.

**Comment by K-vanc** [comment]
are you able to see any channel with epg?? I think there is no epg on website

**Comment by K-vanc** [comment]
Hi, I checked yesterday and siteconfig works fine. There is no url change on siteconfig but website is more restrictive for geo-location now. I could access and grab with my Taiwan VPN but other Asian locations didnt work.
