### ISSUE TITLE
Req : Bein Entertainment (qatar)

### ISSUE THREAD

**Issue by Ahmd916** [K-vanc/Tempest-EPG-Generator#88]
## Issue Type

Please choose your issue type

* [*] Request
* [ ] Bug
* [ ] Question
Site : https://www.bein.com/en/tv-guide

**Comment by K-vanc** [comment]
Hi, since those guides are covering entire MENA, you can find them(entertainment & sport) in Multi Nation folder both as Arabic and English

https://github.com/K-vanc/Tempest-EPG-Generator/blob/main/Siteconfigs/Multi%20Nation/%5BENC%5Dbein.com%5Bentertainment%5D%5Bar%5D_0.siteconfig.php
