### ISSUE TITLE
tvguide us down and multi tvguide too

### ISSUE THREAD

**Issue by Toei79** [K-vanc/Tempest-EPG-Generator#91]
permissions ok, latest version of tempest.php and files too

thanks :)

**Comment by K-vanc** [comment]
Hi @Toei79 

Seems like websites changed. They will be fixed when i am back

**Comment by K-vanc** [comment]
Hi @Toei79

Both siteconfigs are updated

**Comment by Toei79** [comment]
thank you so much! working perfectly :)
