### ISSUE TITLE
Siteconfig request: tvinfo.de

### ISSUE THREAD

**Issue by AngusMacGyver-DE** [K-vanc/Tempest-EPG-Generator#95]
## Issue Type

Please choose your issue type

* [X] Request
* [ ] Bug
* [ ] Question

## OS Details (Not required for Request)

Please choose your OS

* [ ] Windows
* [ ] Unix
* [X] Docker

Please write your version details (Below not required for Docker)

* PHP Version: ...

* Tempest Version: ...

Please write your web server name(Apache/Nginx etc.) or tick shared host if you are running on a shared host service / server (VPS, Web Hosting etc.)

* Web Server Name: ...

* [ ] Shared Host

## Expected Behavior (Not required for Request)

Please describe the behavior you are expecting

## Current Behavior (Not required for Request)

Please describe the current behavior

## Steps to Reproduce (Not required for Request/Question)

Please explain how to reproduce this issue

## Attachments (Not required for Request/Question)

Please attach your error/grab logs, configuration.xml file  

---

Dear K-vanc,

I would like to request an additional Siteconfig for Germany:
[tvinfo.de](https://www.tvinfo.de) 

Reasons:
- Good Quality of Data
- Up to 30 Days available
(- Also available on other well known EPG-Website ;-) )

Best regards,
MacGyver

**Comment by K-vanc** [comment]
hi @AngusMacGyver-DE 

I would accept your request if I wouldn't do it before 😀

It is already available in Germany folder

https://github.com/K-vanc/Tempest-EPG-Generator/blob/5dc1dfce6a9e83d3e64505d768df0e1da37914ca/Siteconfigs/Germany/%5BENC%5Dtvinfo.de_0.siteconfig.php
