### ISSUE TITLE
whattowatch.com[US]_0 URL not found

### ISSUE THREAD

**Issue by stuckinthe** [K-vanc/Tempest-EPG-Generator#96]
## Issue Type

Please choose your issue type

* [ ] Request
* [X ] Bug
* [ ] Question

## OS Details (Not required for Request)

Please choose your OS

* [ ] Windows
* [ X] Unix
* [ ] Docker

Please write your version details (Below not required for Docker)

* PHP Version: ... 8.3.3

* Tempest Version: ...

Please write your web server name(Apache/Nginx etc.) or tick shared host if you are running on a shared host service / server (VPS, Web Hosting etc.)

* Web Server Name: ... Apache

* [ ] Shared Host

## Expected Behavior (Not required for Request)

Guide from whattowatch.com[US]_0 would be downloaded

## Current Behavior (Not required for Request)

Error cannot find URL

## Steps to Reproduce (Not required for Request/Question)

Select some channels from whattowatch.com[US]_0 and try to generate an EPG and all channels will come back as not found

## Attachments (Not required for Request/Question)

Please attach your error/grab logs, configuration.xml file

**Comment by K-vanc** [comment]
Hi @stuckinthe 

Currently there is no epg on the website. Please check website before raising issue..
